# CMake generated Testfile for 
# Source directory: /home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests
# Build directory: /home/andy/test_optimization/openmm-8.4.0/build_test/platforms/reference/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(TestReferenceATMForce "/home/andy/test_optimization/openmm-8.4.0/build_test/TestReferenceATMForce")
set_tests_properties(TestReferenceATMForce PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;19;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;0;")
add_test(TestReferenceAndersenThermostat "/home/andy/test_optimization/openmm-8.4.0/build_test/TestReferenceAndersenThermostat")
set_tests_properties(TestReferenceAndersenThermostat PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;19;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;0;")
add_test(TestReferenceBrownianIntegrator "/home/andy/test_optimization/openmm-8.4.0/build_test/TestReferenceBrownianIntegrator")
set_tests_properties(TestReferenceBrownianIntegrator PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;19;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;0;")
add_test(TestReferenceCMAPTorsionForce "/home/andy/test_optimization/openmm-8.4.0/build_test/TestReferenceCMAPTorsionForce")
set_tests_properties(TestReferenceCMAPTorsionForce PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;19;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;0;")
add_test(TestReferenceCMMotionRemover "/home/andy/test_optimization/openmm-8.4.0/build_test/TestReferenceCMMotionRemover")
set_tests_properties(TestReferenceCMMotionRemover PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;19;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;0;")
add_test(TestReferenceCheckpoints "/home/andy/test_optimization/openmm-8.4.0/build_test/TestReferenceCheckpoints")
set_tests_properties(TestReferenceCheckpoints PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;19;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;0;")
add_test(TestReferenceCompoundIntegrator "/home/andy/test_optimization/openmm-8.4.0/build_test/TestReferenceCompoundIntegrator")
set_tests_properties(TestReferenceCompoundIntegrator PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;19;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;0;")
add_test(TestReferenceConstantPotentialForce "/home/andy/test_optimization/openmm-8.4.0/build_test/TestReferenceConstantPotentialForce")
set_tests_properties(TestReferenceConstantPotentialForce PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;19;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;0;")
add_test(TestReferenceCustomAngleForce "/home/andy/test_optimization/openmm-8.4.0/build_test/TestReferenceCustomAngleForce")
set_tests_properties(TestReferenceCustomAngleForce PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;19;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;0;")
add_test(TestReferenceCustomBondForce "/home/andy/test_optimization/openmm-8.4.0/build_test/TestReferenceCustomBondForce")
set_tests_properties(TestReferenceCustomBondForce PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;19;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;0;")
add_test(TestReferenceCustomCPPForce "/home/andy/test_optimization/openmm-8.4.0/build_test/TestReferenceCustomCPPForce")
set_tests_properties(TestReferenceCustomCPPForce PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;19;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;0;")
add_test(TestReferenceCustomCVForce "/home/andy/test_optimization/openmm-8.4.0/build_test/TestReferenceCustomCVForce")
set_tests_properties(TestReferenceCustomCVForce PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;19;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;0;")
add_test(TestReferenceCustomCentroidBondForce "/home/andy/test_optimization/openmm-8.4.0/build_test/TestReferenceCustomCentroidBondForce")
set_tests_properties(TestReferenceCustomCentroidBondForce PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;19;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;0;")
add_test(TestReferenceCustomCompoundBondForce "/home/andy/test_optimization/openmm-8.4.0/build_test/TestReferenceCustomCompoundBondForce")
set_tests_properties(TestReferenceCustomCompoundBondForce PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;19;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;0;")
add_test(TestReferenceCustomExternalForce "/home/andy/test_optimization/openmm-8.4.0/build_test/TestReferenceCustomExternalForce")
set_tests_properties(TestReferenceCustomExternalForce PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;19;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;0;")
add_test(TestReferenceCustomGBForce "/home/andy/test_optimization/openmm-8.4.0/build_test/TestReferenceCustomGBForce")
set_tests_properties(TestReferenceCustomGBForce PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;19;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;0;")
add_test(TestReferenceCustomHbondForce "/home/andy/test_optimization/openmm-8.4.0/build_test/TestReferenceCustomHbondForce")
set_tests_properties(TestReferenceCustomHbondForce PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;19;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;0;")
add_test(TestReferenceCustomIntegrator "/home/andy/test_optimization/openmm-8.4.0/build_test/TestReferenceCustomIntegrator")
set_tests_properties(TestReferenceCustomIntegrator PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;19;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;0;")
add_test(TestReferenceCustomManyParticleForce "/home/andy/test_optimization/openmm-8.4.0/build_test/TestReferenceCustomManyParticleForce")
set_tests_properties(TestReferenceCustomManyParticleForce PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;19;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;0;")
add_test(TestReferenceCustomNonbondedForce "/home/andy/test_optimization/openmm-8.4.0/build_test/TestReferenceCustomNonbondedForce")
set_tests_properties(TestReferenceCustomNonbondedForce PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;19;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;0;")
add_test(TestReferenceCustomTorsionForce "/home/andy/test_optimization/openmm-8.4.0/build_test/TestReferenceCustomTorsionForce")
set_tests_properties(TestReferenceCustomTorsionForce PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;19;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;0;")
add_test(TestReferenceDPDIntegrator "/home/andy/test_optimization/openmm-8.4.0/build_test/TestReferenceDPDIntegrator")
set_tests_properties(TestReferenceDPDIntegrator PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;19;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;0;")
add_test(TestReferenceDispersionPME "/home/andy/test_optimization/openmm-8.4.0/build_test/TestReferenceDispersionPME")
set_tests_properties(TestReferenceDispersionPME PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;19;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;0;")
add_test(TestReferenceEwald "/home/andy/test_optimization/openmm-8.4.0/build_test/TestReferenceEwald")
set_tests_properties(TestReferenceEwald PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;19;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;0;")
add_test(TestReferenceGBSAOBCForce "/home/andy/test_optimization/openmm-8.4.0/build_test/TestReferenceGBSAOBCForce")
set_tests_properties(TestReferenceGBSAOBCForce PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;19;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;0;")
add_test(TestReferenceGayBerneForce "/home/andy/test_optimization/openmm-8.4.0/build_test/TestReferenceGayBerneForce")
set_tests_properties(TestReferenceGayBerneForce PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;19;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;0;")
add_test(TestReferenceHarmonicAngleForce "/home/andy/test_optimization/openmm-8.4.0/build_test/TestReferenceHarmonicAngleForce")
set_tests_properties(TestReferenceHarmonicAngleForce PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;19;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;0;")
add_test(TestReferenceHarmonicBondForce "/home/andy/test_optimization/openmm-8.4.0/build_test/TestReferenceHarmonicBondForce")
set_tests_properties(TestReferenceHarmonicBondForce PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;19;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;0;")
add_test(TestReferenceKineticEnergy "/home/andy/test_optimization/openmm-8.4.0/build_test/TestReferenceKineticEnergy")
set_tests_properties(TestReferenceKineticEnergy PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;19;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;0;")
add_test(TestReferenceLangevinIntegrator "/home/andy/test_optimization/openmm-8.4.0/build_test/TestReferenceLangevinIntegrator")
set_tests_properties(TestReferenceLangevinIntegrator PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;19;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;0;")
add_test(TestReferenceLangevinMiddleIntegrator "/home/andy/test_optimization/openmm-8.4.0/build_test/TestReferenceLangevinMiddleIntegrator")
set_tests_properties(TestReferenceLangevinMiddleIntegrator PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;19;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;0;")
add_test(TestReferenceLocalEnergyMinimizer "/home/andy/test_optimization/openmm-8.4.0/build_test/TestReferenceLocalEnergyMinimizer")
set_tests_properties(TestReferenceLocalEnergyMinimizer PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;19;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;0;")
add_test(TestReferenceMonteCarloAnisotropicBarostat "/home/andy/test_optimization/openmm-8.4.0/build_test/TestReferenceMonteCarloAnisotropicBarostat")
set_tests_properties(TestReferenceMonteCarloAnisotropicBarostat PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;19;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;0;")
add_test(TestReferenceMonteCarloBarostat "/home/andy/test_optimization/openmm-8.4.0/build_test/TestReferenceMonteCarloBarostat")
set_tests_properties(TestReferenceMonteCarloBarostat PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;19;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;0;")
add_test(TestReferenceMonteCarloFlexibleBarostat "/home/andy/test_optimization/openmm-8.4.0/build_test/TestReferenceMonteCarloFlexibleBarostat")
set_tests_properties(TestReferenceMonteCarloFlexibleBarostat PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;19;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;0;")
add_test(TestReferenceMonteCarloMembraneBarostat "/home/andy/test_optimization/openmm-8.4.0/build_test/TestReferenceMonteCarloMembraneBarostat")
set_tests_properties(TestReferenceMonteCarloMembraneBarostat PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;19;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;0;")
add_test(TestReferenceNeighborList "/home/andy/test_optimization/openmm-8.4.0/build_test/TestReferenceNeighborList")
set_tests_properties(TestReferenceNeighborList PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;19;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;0;")
add_test(TestReferenceNonbondedForce "/home/andy/test_optimization/openmm-8.4.0/build_test/TestReferenceNonbondedForce")
set_tests_properties(TestReferenceNonbondedForce PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;19;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;0;")
add_test(TestReferenceNoseHooverIntegrator "/home/andy/test_optimization/openmm-8.4.0/build_test/TestReferenceNoseHooverIntegrator")
set_tests_properties(TestReferenceNoseHooverIntegrator PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;19;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;0;")
add_test(TestReferenceOrientationRestraintForce "/home/andy/test_optimization/openmm-8.4.0/build_test/TestReferenceOrientationRestraintForce")
set_tests_properties(TestReferenceOrientationRestraintForce PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;19;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;0;")
add_test(TestReferencePeriodicTorsionForce "/home/andy/test_optimization/openmm-8.4.0/build_test/TestReferencePeriodicTorsionForce")
set_tests_properties(TestReferencePeriodicTorsionForce PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;19;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;0;")
add_test(TestReferenceQTBIntegrator "/home/andy/test_optimization/openmm-8.4.0/build_test/TestReferenceQTBIntegrator")
set_tests_properties(TestReferenceQTBIntegrator PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;19;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;0;")
add_test(TestReferenceRBTorsionForce "/home/andy/test_optimization/openmm-8.4.0/build_test/TestReferenceRBTorsionForce")
set_tests_properties(TestReferenceRBTorsionForce PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;19;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;0;")
add_test(TestReferenceRGForce "/home/andy/test_optimization/openmm-8.4.0/build_test/TestReferenceRGForce")
set_tests_properties(TestReferenceRGForce PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;19;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;0;")
add_test(TestReferenceRMSDForce "/home/andy/test_optimization/openmm-8.4.0/build_test/TestReferenceRMSDForce")
set_tests_properties(TestReferenceRMSDForce PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;19;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;0;")
add_test(TestReferenceRandom "/home/andy/test_optimization/openmm-8.4.0/build_test/TestReferenceRandom")
set_tests_properties(TestReferenceRandom PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;19;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;0;")
add_test(TestReferenceSettle "/home/andy/test_optimization/openmm-8.4.0/build_test/TestReferenceSettle")
set_tests_properties(TestReferenceSettle PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;19;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;0;")
add_test(TestReferenceVariableLangevinIntegrator "/home/andy/test_optimization/openmm-8.4.0/build_test/TestReferenceVariableLangevinIntegrator")
set_tests_properties(TestReferenceVariableLangevinIntegrator PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;19;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;0;")
add_test(TestReferenceVariableVerletIntegrator "/home/andy/test_optimization/openmm-8.4.0/build_test/TestReferenceVariableVerletIntegrator")
set_tests_properties(TestReferenceVariableVerletIntegrator PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;19;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;0;")
add_test(TestReferenceVerletIntegrator "/home/andy/test_optimization/openmm-8.4.0/build_test/TestReferenceVerletIntegrator")
set_tests_properties(TestReferenceVerletIntegrator PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;19;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;0;")
add_test(TestReferenceVirtualSites "/home/andy/test_optimization/openmm-8.4.0/build_test/TestReferenceVirtualSites")
set_tests_properties(TestReferenceVirtualSites PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;19;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/reference/tests/CMakeLists.txt;0;")
