# CMake generated Testfile for 
# Source directory: /home/andy/test_optimization/openmm-8.4.0/plugins/amoeba/platforms/cuda/tests
# Build directory: /home/andy/test_optimization/openmm-8.4.0/build_test/plugins/amoeba/platforms/cuda/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(TestCudaAmoebaExtrapolatedPolarizationSingle "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaAmoebaExtrapolatedPolarization" "single")
set_tests_properties(TestCudaAmoebaExtrapolatedPolarizationSingle PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/plugins/amoeba/platforms/cuda/tests/CMakeLists.txt;24;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/plugins/amoeba/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaAmoebaExtrapolatedPolarizationMixed "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaAmoebaExtrapolatedPolarization" "mixed")
set_tests_properties(TestCudaAmoebaExtrapolatedPolarizationMixed PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/plugins/amoeba/platforms/cuda/tests/CMakeLists.txt;26;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/plugins/amoeba/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaAmoebaExtrapolatedPolarizationDouble "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaAmoebaExtrapolatedPolarization" "double")
set_tests_properties(TestCudaAmoebaExtrapolatedPolarizationDouble PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/plugins/amoeba/platforms/cuda/tests/CMakeLists.txt;27;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/plugins/amoeba/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaAmoebaGeneralizedKirkwoodForceSingle "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaAmoebaGeneralizedKirkwoodForce" "single")
set_tests_properties(TestCudaAmoebaGeneralizedKirkwoodForceSingle PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/plugins/amoeba/platforms/cuda/tests/CMakeLists.txt;24;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/plugins/amoeba/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaAmoebaGeneralizedKirkwoodForceMixed "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaAmoebaGeneralizedKirkwoodForce" "mixed")
set_tests_properties(TestCudaAmoebaGeneralizedKirkwoodForceMixed PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/plugins/amoeba/platforms/cuda/tests/CMakeLists.txt;26;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/plugins/amoeba/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaAmoebaGeneralizedKirkwoodForceDouble "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaAmoebaGeneralizedKirkwoodForce" "double")
set_tests_properties(TestCudaAmoebaGeneralizedKirkwoodForceDouble PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/plugins/amoeba/platforms/cuda/tests/CMakeLists.txt;27;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/plugins/amoeba/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaAmoebaMultipoleForceSingle "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaAmoebaMultipoleForce" "single")
set_tests_properties(TestCudaAmoebaMultipoleForceSingle PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/plugins/amoeba/platforms/cuda/tests/CMakeLists.txt;24;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/plugins/amoeba/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaAmoebaMultipoleForceMixed "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaAmoebaMultipoleForce" "mixed")
set_tests_properties(TestCudaAmoebaMultipoleForceMixed PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/plugins/amoeba/platforms/cuda/tests/CMakeLists.txt;26;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/plugins/amoeba/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaAmoebaMultipoleForceDouble "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaAmoebaMultipoleForce" "double")
set_tests_properties(TestCudaAmoebaMultipoleForceDouble PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/plugins/amoeba/platforms/cuda/tests/CMakeLists.txt;27;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/plugins/amoeba/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaAmoebaTorsionTorsionForceSingle "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaAmoebaTorsionTorsionForce" "single")
set_tests_properties(TestCudaAmoebaTorsionTorsionForceSingle PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/plugins/amoeba/platforms/cuda/tests/CMakeLists.txt;24;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/plugins/amoeba/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaAmoebaTorsionTorsionForceMixed "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaAmoebaTorsionTorsionForce" "mixed")
set_tests_properties(TestCudaAmoebaTorsionTorsionForceMixed PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/plugins/amoeba/platforms/cuda/tests/CMakeLists.txt;26;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/plugins/amoeba/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaAmoebaTorsionTorsionForceDouble "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaAmoebaTorsionTorsionForce" "double")
set_tests_properties(TestCudaAmoebaTorsionTorsionForceDouble PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/plugins/amoeba/platforms/cuda/tests/CMakeLists.txt;27;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/plugins/amoeba/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaAmoebaVdwForceSingle "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaAmoebaVdwForce" "single")
set_tests_properties(TestCudaAmoebaVdwForceSingle PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/plugins/amoeba/platforms/cuda/tests/CMakeLists.txt;24;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/plugins/amoeba/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaAmoebaVdwForceMixed "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaAmoebaVdwForce" "mixed")
set_tests_properties(TestCudaAmoebaVdwForceMixed PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/plugins/amoeba/platforms/cuda/tests/CMakeLists.txt;26;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/plugins/amoeba/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaAmoebaVdwForceDouble "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaAmoebaVdwForce" "double")
set_tests_properties(TestCudaAmoebaVdwForceDouble PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/plugins/amoeba/platforms/cuda/tests/CMakeLists.txt;27;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/plugins/amoeba/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaHippoNonbondedForceSingle "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaHippoNonbondedForce" "single")
set_tests_properties(TestCudaHippoNonbondedForceSingle PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/plugins/amoeba/platforms/cuda/tests/CMakeLists.txt;24;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/plugins/amoeba/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaHippoNonbondedForceMixed "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaHippoNonbondedForce" "mixed")
set_tests_properties(TestCudaHippoNonbondedForceMixed PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/plugins/amoeba/platforms/cuda/tests/CMakeLists.txt;26;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/plugins/amoeba/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaHippoNonbondedForceDouble "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaHippoNonbondedForce" "double")
set_tests_properties(TestCudaHippoNonbondedForceDouble PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/plugins/amoeba/platforms/cuda/tests/CMakeLists.txt;27;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/plugins/amoeba/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaWcaDispersionForceSingle "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaWcaDispersionForce" "single")
set_tests_properties(TestCudaWcaDispersionForceSingle PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/plugins/amoeba/platforms/cuda/tests/CMakeLists.txt;24;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/plugins/amoeba/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaWcaDispersionForceMixed "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaWcaDispersionForce" "mixed")
set_tests_properties(TestCudaWcaDispersionForceMixed PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/plugins/amoeba/platforms/cuda/tests/CMakeLists.txt;26;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/plugins/amoeba/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaWcaDispersionForceDouble "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaWcaDispersionForce" "double")
set_tests_properties(TestCudaWcaDispersionForceDouble PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/plugins/amoeba/platforms/cuda/tests/CMakeLists.txt;27;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/plugins/amoeba/platforms/cuda/tests/CMakeLists.txt;0;")
