/* -------------------------------------------------------------------------- *
 *                                   OpenMM                                   *
 * -------------------------------------------------------------------------- *
 * This is part of the OpenMM molecular simulation toolkit.                   *
 * https://openmm.org                                                         *
 *                                                                            *
 * Copyright (c) 2024 Stanford University and the Authors.                    *
 * Authors: Andy (Constant Voltage Integration)                               *
 * -------------------------------------------------------------------------- */

#include "ConstantVoltageKernelSources.h"

using namespace OpenMM;
using namespace std;

const string ConstantVoltageKernelSources::conductorCharge = "/* -------------------------------------------------------------------------- *\n"
" * Conductor Charge Update Kernels (Buckyball / Nanotube)\n"
" * -------------------------------------------------------------------------- *\n"
" * These kernels implement the Numerical_charge_Conductor algorithm from:\n"
" * - MM_classes.py: Numerical_charge_Conductor()\n"
" * - Fixed_Voltage_routines.py: Buckyball_Virtual, Nanotube_Virtual\n"
" *\n"
" * Algorithm:\n"
" * 1. Image charges: Project E-field to surface normal, solve for image charge\n"
" * 2. Charge transfer: Distribute charge to satisfy boundary conditions\n"
" *\n"
" * Reference formulas:\n"
" * - Image charge:   q_i = (2 / 4) * area_atom * En_external * K\n"
" * - Buckyball dQ:   dQ = -dE * dr_center_contact\n"
" * - Nanotube dQ:    dQ = -dE * dr_center_contact * length / 2\n"
" * -------------------------------------------------------------------------- */\n"
"\n"
"// Conversion constants\n"
"#define CONVERSION_KJMOL_NM_AU 0.00719475f\n"
"#define FOUR_PI 12.566370614359172f\n"
"#define SMALL_THRESHOLD 1e-6f\n"
"\n"
"// Conductor types\n"
"#define CONDUCTOR_BUCKYBALL 0\n"
"#define CONDUCTOR_NANOTUBE  1\n"
"\n"
"\n"
"/**\n"
" * Compute image charges on conductor surface atoms.\n"
" * \n"
" * Step 1 of Numerical_charge_Conductor:\n"
" * For each atom, project electric field onto surface normal,\n"
" * then solve for image charge that cancels normal field inside.\n"
" *\n"
" * @param numAtoms            Number of atoms in this conductor\n"
" * @param conductorIndices    Particle indices in the conductor\n"
" * @param conductorNormals    Surface normal (nx, ny, nz) for each atom\n"
" * @param areaPerAtom         Area associated with each conductor atom\n"
" * @param posq                Particle positions and charges\n"
" * @param forceBuffer         Force buffer (fixed-point, needs scaling)\n"
" * @param paddedNumAtoms      Padded atom count for force buffer indexing\n"
" * @param smallThreshold      Minimum charge threshold\n"
" */\n"
"extern \"C\" __global__ void computeConductorImageCharges(\n"
"    int numAtoms,\n"
"    const int* __restrict__ conductorIndices,\n"
"    const float4* __restrict__ conductorNormals,  // (nx, ny, nz, unused)\n"
"    float areaPerAtom,\n"
"    float4* __restrict__ posq,\n"
"    const long long* __restrict__ forceBuffer,\n"
"    int paddedNumAtoms,\n"
"    float smallThreshold\n"
") {\n"
"    int idx = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    if (idx >= numAtoms) return;\n"
"    \n"
"    int particleIdx = conductorIndices[idx];\n"
"    \n"
"    // Get current charge\n"
"    float4 pos = posq[particleIdx];\n"
"    float q_current = pos.w;\n"
"    \n"
"    // Skip if charge too small (can't compute E from F)\n"
"    if (fabsf(q_current) < 0.9f * smallThreshold) {\n"
"        // Set to small positive value\n"
"        posq[particleIdx].w = smallThreshold;\n"
"        return;\n"
"    }\n"
"    \n"
"    // Read forces (fixed-point to float)\n"
"    const float forceScale = 1.0f / 0x100000000;\n"
"    float Fx = forceBuffer[particleIdx] * forceScale;\n"
"    float Fy = forceBuffer[particleIdx + paddedNumAtoms] * forceScale;\n"
"    float Fz = forceBuffer[particleIdx + 2 * paddedNumAtoms] * forceScale;\n"
"    \n"
"    // E = F / q\n"
"    float Ex = Fx / q_current;\n"
"    float Ey = Fy / q_current;\n"
"    float Ez = Fz / q_current;\n"
"    \n"
"    // Project onto surface normal\n"
"    float4 normal = conductorNormals[idx];\n"
"    float En = Ex * normal.x + Ey * normal.y + Ez * normal.z;\n"
"    \n"
"    // Image charge formula:\n"
"    // q_i = (2 / 4) * area * En * conversion\n"
"    float q_new = (2.0f / FOUR_PI) * areaPerAtom * En * CONVERSION_KJMOL_NM_AU;\n"
"    \n"
"    // Update charge in posq\n"
"    posq[particleIdx].w = q_new;\n"
"}\n"
"\n"
"\n"
"/**\n"
" * Compute charge transfer for conductor boundary condition.\n"
" *\n"
" * Step 2 of Numerical_charge_Conductor:\n"
" * Based on contact with electrode or another conductor,\n"
" * compute the charge transfer to satisfy equipotential.\n"
" *\n"
" * @param numAtoms            Number of atoms in this conductor\n"
" * @param conductorIndices    Particle indices in the conductor\n"
" * @param contactAtomIdx      Index of the contact atom (for field reading)\n"
" * @param contactNormal       Normal vector at contact atom\n"
" * @param conductorType       0 = Buckyball, 1 = Nanotube\n"
" * @param drCenterContact     Distance from conductor center to contact point\n"
" * @param conductorLength     Length (for Nanotube only)\n"
" * @param isCloseToElectrode  True if contact is with primary electrode\n"
" * @param voltage             Applied voltage (kJ/mol/e)\n"
" * @param Lgap                Electrode gap (nm)\n"
" * @param posq                Particle positions and charges\n"
" * @param forceBuffer         Force buffer\n"
" * @param paddedNumAtoms      Padded atom count\n"
" */\n"
"extern \"C\" __global__ void computeConductorChargeTransfer(\n"
"    int numAtoms,\n"
"    const int* __restrict__ conductorIndices,\n"
"    int contactAtomIdx,\n"
"    float3 contactNormal,\n"
"    int conductorType,\n"
"    float drCenterContact,\n"
"    float conductorLength,\n"
"    int isCloseToElectrode,\n"
"    float voltage,\n"
"    float Lgap,\n"
"    float4* __restrict__ posq,\n"
"    const long long* __restrict__ forceBuffer,\n"
"    int paddedNumAtoms\n"
") {\n"
"    // Only thread 0 computes the charge transfer, then broadcasts\n"
"    __shared__ float dq_per_atom;\n"
"    \n"
"    if (threadIdx.x == 0 && blockIdx.x == 0) {\n"
"        // Read force on contact atom\n"
"        const float forceScale = 1.0f / 0x100000000;\n"
"        float Fx = forceBuffer[contactAtomIdx] * forceScale;\n"
"        float Fy = forceBuffer[contactAtomIdx + paddedNumAtoms] * forceScale;\n"
"        float Fz = forceBuffer[contactAtomIdx + 2 * paddedNumAtoms] * forceScale;\n"
"        \n"
"        float q_contact = posq[contactAtomIdx].w;\n"
"        float En_external = 0.0f;\n"
"        \n"
"        if (fabsf(q_contact) > SMALL_THRESHOLD) {\n"
"            float Ex = Fx / q_contact;\n"
"            float Ey = Fy / q_contact;\n"
"            float Ez = Fz / q_contact;\n"
"            En_external = Ex * contactNormal.x + Ey * contactNormal.y + Ez * contactNormal.z;\n"
"        }\n"
"        \n"
"        // Compute dE based on contact type\n"
"        float dE_conductor;\n"
"        if (isCloseToElectrode) {\n"
"            // Contact with primary electrode\n"
"            // dE = -(En + V/Lgap/2) * K\n"
"            dE_conductor = -(En_external + voltage / Lgap / 2.0f) * CONVERSION_KJMOL_NM_AU;\n"
"        } else {\n"
"            // Contact with another conductor\n"
"            // dE = -En * K\n"
"            dE_conductor = -En_external * CONVERSION_KJMOL_NM_AU;\n"
"        }\n"
"        \n"
"        // Geometry-dependent charge transfer\n"
"        float dQ_conductor;\n"
"        float sign = -1.0f;  // positive z displacement from cathode  negative field for positive charge\n"
"        \n"
"        if (conductorType == CONDUCTOR_BUCKYBALL) {\n"
"            // Spherical: Q = E * A / 4,  A = 4 * r    Q = E * r\n"
"            dQ_conductor = sign * dE_conductor * drCenterContact * drCenterContact;\n"
"        } else {  // CONDUCTOR_NANOTUBE\n"
"            // Cylindrical: Q = E * A / 4,  A = 2 * r * L    Q = E * r * L / 2\n"
"            dQ_conductor = sign * dE_conductor * drCenterContact * conductorLength / 2.0f;\n"
"        }\n"
"        \n"
"        // Per-atom charge\n"
"        dq_per_atom = dQ_conductor / (float)numAtoms;\n"
"    }\n"
"    \n"
"    __syncthreads();\n"
"    \n"
"    // All threads add the charge to their atoms\n"
"    int idx = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    if (idx >= numAtoms) return;\n"
"    \n"
"    int particleIdx = conductorIndices[idx];\n"
"    posq[particleIdx].w += dq_per_atom;\n"
"}\n"
"\n"
"\n"
"/**\n"
" * Scale all electrode and conductor charges to analytic normalization.\n"
" *\n"
" * When conductors are present:\n"
" * - Anode scaled normally (independent)\n"
" * - Q_analytic = -Anode.Q_analytic\n"
" * - Q_numeric_total = Cathode_total + sum(Conductor_total)\n"
" * - scale_factor = Q_analytic / Q_numeric_total\n"
" * - Apply scale_factor to cathode + all conductors\n"
" *\n"
" * @param numCathodeAtoms     Number of cathode atoms\n"
" * @param cathodeIndices      Cathode atom indices\n"
" * @param numConductorAtoms   Total conductor atoms (all conductors combined)\n"
" * @param conductorIndices    Conductor atom indices (flattened)\n"
" * @param qAnalyticAnode      Analytic charge on anode (already computed)\n"
" * @param posq                Particle positions and charges\n"
" * @param smallThreshold      Minimum threshold to avoid division by zero\n"
" */\n"
"extern \"C\" __global__ void scaleElectrodeChargesWithConductors(\n"
"    int numCathodeAtoms,\n"
"    const int* __restrict__ cathodeIndices,\n"
"    int numConductorAtoms,\n"
"    const int* __restrict__ conductorIndices,\n"
"    float qAnalyticAnode,\n"
"    float4* __restrict__ posq,\n"
"    float smallThreshold\n"
") {\n"
"    // Step 1: Compute total numeric charge on cathode + conductors\n"
"    // Use reduction pattern\n"
"    __shared__ float sdata[256];\n"
"    \n"
"    float localSum = 0.0f;\n"
"    \n"
"    // Sum cathode charges\n"
"    for (int i = threadIdx.x; i < numCathodeAtoms; i += blockDim.x) {\n"
"        int pIdx = cathodeIndices[i];\n"
"        localSum += posq[pIdx].w;\n"
"    }\n"
"    \n"
"    // Sum conductor charges\n"
"    for (int i = threadIdx.x; i < numConductorAtoms; i += blockDim.x) {\n"
"        int pIdx = conductorIndices[i];\n"
"        localSum += posq[pIdx].w;\n"
"    }\n"
"    \n"
"    sdata[threadIdx.x] = localSum;\n"
"    __syncthreads();\n"
"    \n"
"    // Reduction\n"
"    for (int s = blockDim.x / 2; s > 0; s >>= 1) {\n"
"        if (threadIdx.x < s) {\n"
"            sdata[threadIdx.x] += sdata[threadIdx.x + s];\n"
"        }\n"
"        __syncthreads();\n"
"    }\n"
"    \n"
"    __shared__ float scaleFactor;\n"
"    if (threadIdx.x == 0) {\n"
"        float qNumericTotal = sdata[0];\n"
"        float qAnalytic = -qAnalyticAnode;  // opposite sign\n"
"        \n"
"        if (fabsf(qNumericTotal) > smallThreshold) {\n"
"            scaleFactor = qAnalytic / qNumericTotal;\n"
"        } else {\n"
"            scaleFactor = 1.0f;  // no scaling\n"
"        }\n"
"    }\n"
"    __syncthreads();\n"
"    \n"
"    // Apply scale factor if positive\n"
"    if (scaleFactor > 0.0f) {\n"
"        // Scale cathode\n"
"        for (int i = threadIdx.x; i < numCathodeAtoms; i += blockDim.x) {\n"
"            int pIdx = cathodeIndices[i];\n"
"            posq[pIdx].w *= scaleFactor;\n"
"        }\n"
"        \n"
"        // Scale conductors\n"
"        for (int i = threadIdx.x; i < numConductorAtoms; i += blockDim.x) {\n"
"            int pIdx = conductorIndices[i];\n"
"            posq[pIdx].w *= scaleFactor;\n"
"        }\n"
"    }\n"
"}\n"
"\n"
"\n"
"/**\n"
" * Initialize conductor geometry (center, radius, normals).\n"
" * Called once during setup, not per-step.\n"
" *\n"
" * @param numAtoms          Number of atoms in conductor\n"
" * @param conductorIndices  Particle indices\n"
" * @param conductorType     0 = Buckyball, 1 = Nanotube\n"
" * @param axis              Nanotube axis (ignored for Buckyball)\n"
" * @param posq              Particle positions\n"
" * @param normals           Output: surface normals\n"
" * @param center            Output: conductor center\n"
" * @param radius            Output: conductor radius\n"
" */\n"
"extern \"C\" __global__ void initConductorGeometry(\n"
"    int numAtoms,\n"
"    const int* __restrict__ conductorIndices,\n"
"    int conductorType,\n"
"    float3 axis,\n"
"    const float4* __restrict__ posq,\n"
"    float4* __restrict__ normals,\n"
"    float3* center,\n"
"    float* radius\n"
") {\n"
"    // First, compute center (parallel reduction)\n"
"    __shared__ float3 sdata3[256];\n"
"    \n"
"    float3 localSum = make_float3(0.0f, 0.0f, 0.0f);\n"
"    for (int i = threadIdx.x; i < numAtoms; i += blockDim.x) {\n"
"        int pIdx = conductorIndices[i];\n"
"        float4 pos = posq[pIdx];\n"
"        localSum.x += pos.x;\n"
"        localSum.y += pos.y;\n"
"        localSum.z += pos.z;\n"
"    }\n"
"    \n"
"    sdata3[threadIdx.x] = localSum;\n"
"    __syncthreads();\n"
"    \n"
"    // Reduction for center\n"
"    for (int s = blockDim.x / 2; s > 0; s >>= 1) {\n"
"        if (threadIdx.x < s) {\n"
"            sdata3[threadIdx.x].x += sdata3[threadIdx.x + s].x;\n"
"            sdata3[threadIdx.x].y += sdata3[threadIdx.x + s].y;\n"
"            sdata3[threadIdx.x].z += sdata3[threadIdx.x + s].z;\n"
"        }\n"
"        __syncthreads();\n"
"    }\n"
"    \n"
"    __shared__ float3 sharedCenter;\n"
"    __shared__ float sharedRadius;\n"
"    \n"
"    if (threadIdx.x == 0) {\n"
"        sharedCenter.x = sdata3[0].x / numAtoms;\n"
"        sharedCenter.y = sdata3[0].y / numAtoms;\n"
"        sharedCenter.z = sdata3[0].z / numAtoms;\n"
"        *center = sharedCenter;\n"
"        sharedRadius = 0.0f;\n"
"    }\n"
"    __syncthreads();\n"
"    \n"
"    // Compute radius and normals\n"
"    for (int i = threadIdx.x; i < numAtoms; i += blockDim.x) {\n"
"        int pIdx = conductorIndices[i];\n"
"        float4 pos = posq[pIdx];\n"
"        \n"
"        float dx = pos.x - sharedCenter.x;\n"
"        float dy = pos.y - sharedCenter.y;\n"
"        float dz = pos.z - sharedCenter.z;\n"
"        \n"
"        float3 radialVec;\n"
"        \n"
"        if (conductorType == CONDUCTOR_NANOTUBE) {\n"
"            // Project out component along axis\n"
"            float axisProj = dx * axis.x + dy * axis.y + dz * axis.z;\n"
"            radialVec.x = dx - axisProj * axis.x;\n"
"            radialVec.y = dy - axisProj * axis.y;\n"
"            radialVec.z = dz - axisProj * axis.z;\n"
"        } else {  // BUCKYBALL\n"
"            radialVec.x = dx;\n"
"            radialVec.y = dy;\n"
"            radialVec.z = dz;\n"
"        }\n"
"        \n"
"        float r = sqrtf(radialVec.x * radialVec.x + radialVec.y * radialVec.y + radialVec.z * radialVec.z);\n"
"        \n"
"        // Store normal\n"
"        if (r > 1e-8f) {\n"
"            normals[i] = make_float4(radialVec.x / r, radialVec.y / r, radialVec.z / r, 0.0f);\n"
"        } else {\n"
"            normals[i] = make_float4(0.0f, 0.0f, 1.0f, 0.0f);\n"
"        }\n"
"        \n"
"        // First thread with valid radius sets it\n"
"        if (i == 0) {\n"
"            sharedRadius = r;\n"
"            *radius = r;\n"
"        }\n"
"    }\n"
"}\n"
"";
const string ConstantVoltageKernelSources::constantVoltage = "/**\n"
" * ConstantVoltage CUDA Kernels\n"
" * \n"
" * GPU-native implementation of SCF electrode charge updates.\n"
" * Based on Professor McDaniel's Python algorithm.\n"
" * \n"
" * CRITICAL OPENMM CONVENTIONS:\n"
" * 1. posq = float4(x, y, z, charge)\n"
" * 2. LongForceBuffer = int64 fixed-point, scale = 0x100000000\n"
" * 3. Force layout: Fx at [i], Fy at [i+paddedNumAtoms], Fz at [i+2*paddedNumAtoms]\n"
" */\n"
"\n"
"// Physical constants (from Fixed_Voltage_routines.py)\n"
"#ifndef CONVERSION_KJMOL_NM_AU\n"
"#define CONVERSION_KJMOL_NM_AU 0.00719475f  // 18.8973/2625.5\n"
"#endif\n"
"\n"
"#ifndef FOUR_PI\n"
"#define FOUR_PI 12.566370614359172f\n"
"#endif\n"
"\n"
"#ifndef SMALL_THRESHOLD\n"
"#define SMALL_THRESHOLD 1e-6f\n"
"#endif\n"
"\n"
"// Fixed-point force scale (from OpenMM convention)\n"
"#define FORCE_SCALE (1.0f / 4294967296.0f)  // 1.0 / 0x100000000\n"
"\n"
"/**\n"
" * Update cathode electrode charges based on SCF iteration.\n"
" * \n"
" * Python Original (MM_classes.py:323-335):\n"
" *   Ez_external = forces[index][2] / q_i_old  if |q_i_old| > 0.9*small_threshold else 0\n"
" *   q_i = 2.0 / (4.0 * pi) * area * (V/Lgap + Ez) * conversion\n"
" *   if |q_i| < threshold: q_i = threshold (positive for cathode)\n"
" */\n"
"extern \"C\" __global__ void updateCathodeCharges(\n"
"    float4* __restrict__ posq,\n"
"    const long long* __restrict__ forceBuffer,\n"
"    const int* __restrict__ cathodeIndices,\n"
"    const float* __restrict__ cathodeAreas,\n"
"    int numCathodes,\n"
"    int paddedNumAtoms,\n"
"    float voltage_kjmol,\n"
"    float Lgap)\n"
"{\n"
"    int idx = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    if (idx >= numCathodes) return;\n"
"    \n"
"    int atomIndex = cathodeIndices[idx];\n"
"    float area = cathodeAreas[idx];\n"
"    \n"
"    // Get current charge\n"
"    float q_old = posq[atomIndex].w;\n"
"    \n"
"    // Get Ez from force buffer (z-component)\n"
"    // Force layout: Fz at [atomIndex + 2*paddedNumAtoms]\n"
"    long long fz_fixed = forceBuffer[atomIndex + 2 * paddedNumAtoms];\n"
"    float fz = ((float)fz_fixed) * FORCE_SCALE;\n"
"    \n"
"    // Compute external field: Ez = Fz / q\n"
"    float Ez_external = 0.0f;\n"
"    if (fabsf(q_old) > 0.9f * SMALL_THRESHOLD) {\n"
"        Ez_external = fz / q_old;\n"
"    }\n"
"    \n"
"    // New charge from boundary condition: q = (2/4) * area * (V/Lgap + Ez) * K\n"
"    // For CATHODE: positive voltage, positive charge\n"
"    float q_new = (2.0f / FOUR_PI) * area * (voltage_kjmol / Lgap + Ez_external) * CONVERSION_KJMOL_NM_AU;\n"
"    \n"
"    // Prevent charge from getting too small (numerical stability)\n"
"    if (fabsf(q_new) < SMALL_THRESHOLD) {\n"
"        q_new = SMALL_THRESHOLD;  // Cathode: positive\n"
"    }\n"
"    \n"
"    // Update charge in posq\n"
"    posq[atomIndex].w = q_new;\n"
"}\n"
"\n"
"/**\n"
" * Update anode electrode charges based on SCF iteration.\n"
" * \n"
" * Python Original (MM_classes.py:338-350):\n"
" *   Same as cathode but with negative sign\n"
" *   q_i = -2.0 / (4.0 * pi) * area * (V/Lgap + Ez) * conversion\n"
" *   if |q_i| < threshold: q_i = -threshold (negative for anode)\n"
" */\n"
"extern \"C\" __global__ void updateAnodeCharges(\n"
"    float4* __restrict__ posq,\n"
"    const long long* __restrict__ forceBuffer,\n"
"    const int* __restrict__ anodeIndices,\n"
"    const float* __restrict__ anodeAreas,\n"
"    int numAnodes,\n"
"    int paddedNumAtoms,\n"
"    float voltage_kjmol,\n"
"    float Lgap)\n"
"{\n"
"    int idx = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    if (idx >= numAnodes) return;\n"
"    \n"
"    int atomIndex = anodeIndices[idx];\n"
"    float area = anodeAreas[idx];\n"
"    \n"
"    // Get current charge\n"
"    float q_old = posq[atomIndex].w;\n"
"    \n"
"    // Get Ez from force buffer\n"
"    long long fz_fixed = forceBuffer[atomIndex + 2 * paddedNumAtoms];\n"
"    float fz = ((float)fz_fixed) * FORCE_SCALE;\n"
"    \n"
"    // Compute external field\n"
"    float Ez_external = 0.0f;\n"
"    if (fabsf(q_old) > 0.9f * SMALL_THRESHOLD) {\n"
"        Ez_external = fz / q_old;\n"
"    }\n"
"    \n"
"    // New charge: ANODE = negative sign\n"
"    float q_new = -(2.0f / FOUR_PI) * area * (voltage_kjmol / Lgap + Ez_external) * CONVERSION_KJMOL_NM_AU;\n"
"    \n"
"    // Prevent charge from getting too small (numerical stability)\n"
"    if (fabsf(q_new) < SMALL_THRESHOLD) {\n"
"        q_new = -SMALL_THRESHOLD;  // Anode: negative\n"
"    }\n"
"    \n"
"    // Update charge in posq\n"
"    posq[atomIndex].w = q_new;\n"
"}\n"
"\n"
"/**\n"
" * Compute total charge on electrode (parallel reduction).\n"
" * \n"
" * Uses atomic add for simple implementation.\n"
" * For production, should use proper parallel reduction.\n"
" */\n"
"extern \"C\" __global__ void computeElectrodeCharge(\n"
"    const float4* __restrict__ posq,\n"
"    const int* __restrict__ electrodeIndices,\n"
"    int numElectrode,\n"
"    float* __restrict__ totalCharge)\n"
"{\n"
"    int idx = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    if (idx >= numElectrode) return;\n"
"    \n"
"    int atomIndex = electrodeIndices[idx];\n"
"    float charge = posq[atomIndex].w;\n"
"    \n"
"    atomicAdd(totalCharge, charge);\n"
"}\n"
"\n"
"/**\n"
" * Compute analytic charge based on Green's Reciprocity.\n"
" * \n"
" * Python Original (Fixed_Voltage_routines.py:318-344):\n"
" *   Q_analytic = sign / (4*pi) * sheet_area * (V/Lgap + V/Lcell) * K\n"
" *   \n"
" *   For each electrolyte atom:\n"
" *     z_distance = |z_atom - z_opposite|\n"
" *     Q_analytic += (z_distance / Lcell) * (-q_i)\n"
" * \n"
" * This kernel computes the image charge contribution.\n"
" */\n"
"extern \"C\" __global__ void computeAnalyticCharge(\n"
"    const float4* __restrict__ posq,\n"
"    const int* __restrict__ electrolyteIndices,\n"
"    int numElectrolytes,\n"
"    float z_opposite,\n"
"    float Lcell,\n"
"    float* __restrict__ analyticCharge)\n"
"{\n"
"    int idx = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    if (idx >= numElectrolytes) return;\n"
"    \n"
"    int atomIndex = electrolyteIndices[idx];\n"
"    float z_atom = posq[atomIndex].z;\n"
"    float q_i = posq[atomIndex].w;\n"
"    \n"
"    // Image charge contribution: (|z - z_opposite| / Lcell) * (-q)\n"
"    float z_distance = fabsf(z_atom - z_opposite);\n"
"    float contribution = (z_distance / Lcell) * (-q_i);\n"
"    \n"
"    atomicAdd(analyticCharge, contribution);\n"
"}\n"
"\n"
"/**\n"
" * Scale electrode charges to match analytic normalization.\n"
" * \n"
" * Python Original (MM_classes.py:536-545):\n"
" *   scale_factor = Q_analytic / Q_numeric_total\n"
" *   for atom in electrode_atoms:\n"
" *       atom.charge = atom.charge * scale_factor\n"
" */\n"
"extern \"C\" __global__ void scaleElectrodeCharges(\n"
"    float4* __restrict__ posq,\n"
"    const int* __restrict__ electrodeIndices,\n"
"    int numElectrode,\n"
"    float scaleFactor)\n"
"{\n"
"    int idx = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    if (idx >= numElectrode) return;\n"
"    \n"
"    int atomIndex = electrodeIndices[idx];\n"
"    posq[atomIndex].w *= scaleFactor;\n"
"}\n"
"";
const string ConstantVoltageKernelSources::drudeLangevin = "/**\n"
" * ConstantVoltage Drude Langevin CUDA Kernels\n"
" * \n"
" * GPU-native implementation of Drude Langevin dynamics with dual-temperature thermostat.\n"
" * Directly copied from OpenMM's drudeLangevin.cc with CUDA-specific modifications.\n"
" * \n"
" * This file is compiled via JIT and should use CUDA-compatible syntax.\n"
" */\n"
"\n"
"// \n"
"// Drude Langevin Integration Part 1: Velocity Update with Dual-Temperature\n"
"// \n"
"\n"
"/**\n"
" * Perform the first step of Langevin integration.\n"
" * \n"
" * Updates velocities using:\n"
" * - vscale, fscale, noisescale for normal particles (system temperature)\n"
" * - vscaleDrude, fscaleDrude, noisescaleDrude for Drude pairs (Drude temperature)\n"
" */\n"
"extern \"C\" __global__ void integrateDrudeLangevinPart1(\n"
"    float4* __restrict__ velm,\n"
"    const long long* __restrict__ forceBuffer,\n"
"    float4* __restrict__ posDelta,\n"
"    const int* __restrict__ normalParticles,\n"
"    const int2* __restrict__ pairParticles,\n"
"    const float2* __restrict__ stepSizeBuffer,\n"
"    float vscale,\n"
"    float fscale,\n"
"    float noisescale,\n"
"    float vscaleDrude,\n"
"    float fscaleDrude,\n"
"    float noisescaleDrude,\n"
"    const float4* __restrict__ random,\n"
"    unsigned int randomIndex,\n"
"    int numNormalParticles,\n"
"    int numPairs,\n"
"    int paddedNumAtoms)\n"
"{\n"
"    float stepSize = stepSizeBuffer[0].y;\n"
"    \n"
"    // Fixed-point force scale\n"
"    const float FORCE_SCALE = 1.0f / 4294967296.0f;  // 1/0x100000000\n"
"    \n"
"    // Update normal particles\n"
"    int idx = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    \n"
"    if (idx < numNormalParticles) {\n"
"        int index = normalParticles[idx];\n"
"        float4 velocity = velm[index];\n"
"        if (velocity.w != 0.0f) {\n"
"            float sqrtInvMass = sqrtf(velocity.w);\n"
"            float4 rand = random[randomIndex + index];\n"
"            \n"
"            // Read forces and convert from fixed-point\n"
"            float fx = ((float)forceBuffer[index]) * FORCE_SCALE;\n"
"            float fy = ((float)forceBuffer[index + paddedNumAtoms]) * FORCE_SCALE;\n"
"            float fz = ((float)forceBuffer[index + 2*paddedNumAtoms]) * FORCE_SCALE;\n"
"            \n"
"            velocity.x = vscale*velocity.x + fscale*velocity.w*fx + noisescale*sqrtInvMass*rand.x;\n"
"            velocity.y = vscale*velocity.y + fscale*velocity.w*fy + noisescale*sqrtInvMass*rand.y;\n"
"            velocity.z = vscale*velocity.z + fscale*velocity.w*fz + noisescale*sqrtInvMass*rand.z;\n"
"            \n"
"            velm[index] = velocity;\n"
"            posDelta[index] = make_float4(stepSize*velocity.x, stepSize*velocity.y, stepSize*velocity.z, 0.0f);\n"
"        }\n"
"    }\n"
"}\n"
"\n"
"/**\n"
" * Update Drude particle pairs with dual-temperature thermostat.\n"
" * \n"
" * For Drude pairs:\n"
" * - Center of mass uses system temperature\n"
" * - Relative motion uses Drude (cold) temperature\n"
" */\n"
"extern \"C\" __global__ void integrateDrudePairs(\n"
"    float4* __restrict__ velm,\n"
"    const long long* __restrict__ forceBuffer,\n"
"    float4* __restrict__ posDelta,\n"
"    const int2* __restrict__ pairParticles,\n"
"    const float2* __restrict__ stepSizeBuffer,\n"
"    float vscale,\n"
"    float fscale,\n"
"    float noisescale,\n"
"    float vscaleDrude,\n"
"    float fscaleDrude,\n"
"    float noisescaleDrude,\n"
"    const float4* __restrict__ random,\n"
"    unsigned int randomIndex,\n"
"    int numPairs,\n"
"    int paddedNumAtoms)\n"
"{\n"
"    float stepSize = stepSizeBuffer[0].y;\n"
"    const float FORCE_SCALE = 1.0f / 4294967296.0f;\n"
"    \n"
"    int idx = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    if (idx >= numPairs) return;\n"
"    \n"
"    int2 particles = pairParticles[idx];\n"
"    float4 velocity1 = velm[particles.x];\n"
"    float4 velocity2 = velm[particles.y];\n"
"    \n"
"    float mass1 = 1.0f / velocity1.w;\n"
"    float mass2 = 1.0f / velocity2.w;\n"
"    float invTotalMass = 1.0f / (mass1 + mass2);\n"
"    float invReducedMass = (mass1 + mass2) * velocity1.w * velocity2.w;\n"
"    float mass1fract = invTotalMass * mass1;\n"
"    float mass2fract = invTotalMass * mass2;\n"
"    float sqrtInvTotalMass = sqrtf(invTotalMass);\n"
"    float sqrtInvReducedMass = sqrtf(invReducedMass);\n"
"    \n"
"    // Center of mass velocity\n"
"    float4 cmVel = make_float4(\n"
"        velocity1.x*mass1fract + velocity2.x*mass2fract,\n"
"        velocity1.y*mass1fract + velocity2.y*mass2fract,\n"
"        velocity1.z*mass1fract + velocity2.z*mass2fract,\n"
"        0.0f\n"
"    );\n"
"    \n"
"    // Relative velocity\n"
"    float4 relVel = make_float4(\n"
"        velocity2.x - velocity1.x,\n"
"        velocity2.y - velocity1.y,\n"
"        velocity2.z - velocity1.z,\n"
"        0.0f\n"
"    );\n"
"    \n"
"    // Read forces\n"
"    float3 force1 = make_float3(\n"
"        ((float)forceBuffer[particles.x]) * FORCE_SCALE,\n"
"        ((float)forceBuffer[particles.x + paddedNumAtoms]) * FORCE_SCALE,\n"
"        ((float)forceBuffer[particles.x + 2*paddedNumAtoms]) * FORCE_SCALE\n"
"    );\n"
"    float3 force2 = make_float3(\n"
"        ((float)forceBuffer[particles.y]) * FORCE_SCALE,\n"
"        ((float)forceBuffer[particles.y + paddedNumAtoms]) * FORCE_SCALE,\n"
"        ((float)forceBuffer[particles.y + 2*paddedNumAtoms]) * FORCE_SCALE\n"
"    );\n"
"    \n"
"    float3 cmForce = make_float3(force1.x + force2.x, force1.y + force2.y, force1.z + force2.z);\n"
"    float3 relForce = make_float3(\n"
"        force2.x*mass1fract - force1.x*mass2fract,\n"
"        force2.y*mass1fract - force1.y*mass2fract,\n"
"        force2.z*mass1fract - force1.z*mass2fract\n"
"    );\n"
"    \n"
"    // Random numbers for thermal noise\n"
"    float4 rand1 = random[randomIndex + 2*idx];\n"
"    float4 rand2 = random[randomIndex + 2*idx + 1];\n"
"    \n"
"    // Update center of mass velocity (system temperature)\n"
"    cmVel.x = vscale*cmVel.x + fscale*invTotalMass*cmForce.x + noisescale*sqrtInvTotalMass*rand1.x;\n"
"    cmVel.y = vscale*cmVel.y + fscale*invTotalMass*cmForce.y + noisescale*sqrtInvTotalMass*rand1.y;\n"
"    cmVel.z = vscale*cmVel.z + fscale*invTotalMass*cmForce.z + noisescale*sqrtInvTotalMass*rand1.z;\n"
"    \n"
"    // Update relative velocity (Drude temperature - cold)\n"
"    relVel.x = vscaleDrude*relVel.x + fscaleDrude*invReducedMass*relForce.x + noisescaleDrude*sqrtInvReducedMass*rand2.x;\n"
"    relVel.y = vscaleDrude*relVel.y + fscaleDrude*invReducedMass*relForce.y + noisescaleDrude*sqrtInvReducedMass*rand2.y;\n"
"    relVel.z = vscaleDrude*relVel.z + fscaleDrude*invReducedMass*relForce.z + noisescaleDrude*sqrtInvReducedMass*rand2.z;\n"
"    \n"
"    // Reconstruct individual velocities\n"
"    velocity1.x = cmVel.x - relVel.x*mass2fract;\n"
"    velocity1.y = cmVel.y - relVel.y*mass2fract;\n"
"    velocity1.z = cmVel.z - relVel.z*mass2fract;\n"
"    velocity2.x = cmVel.x + relVel.x*mass1fract;\n"
"    velocity2.y = cmVel.y + relVel.y*mass1fract;\n"
"    velocity2.z = cmVel.z + relVel.z*mass1fract;\n"
"    \n"
"    velm[particles.x] = velocity1;\n"
"    velm[particles.y] = velocity2;\n"
"    posDelta[particles.x] = make_float4(stepSize*velocity1.x, stepSize*velocity1.y, stepSize*velocity1.z, 0.0f);\n"
"    posDelta[particles.y] = make_float4(stepSize*velocity2.x, stepSize*velocity2.y, stepSize*velocity2.z, 0.0f);\n"
"}\n"
"\n"
"// \n"
"// Drude Langevin Integration Part 2: Position Update\n"
"// \n"
"\n"
"extern \"C\" __global__ void integrateDrudeLangevinPart2(\n"
"    float4* __restrict__ posq,\n"
"    const float4* __restrict__ posDelta,\n"
"    float4* __restrict__ velm,\n"
"    const float2* __restrict__ stepSizeBuffer,\n"
"    int numAtoms)\n"
"{\n"
"    float invStepSize = 1.0f / stepSizeBuffer[0].y;\n"
"    \n"
"    int idx = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    if (idx >= numAtoms) return;\n"
"    \n"
"    float4 vel = velm[idx];\n"
"    if (vel.w != 0.0f) {\n"
"        float4 pos = posq[idx];\n"
"        float4 delta = posDelta[idx];\n"
"        \n"
"        pos.x += delta.x;\n"
"        pos.y += delta.y;\n"
"        pos.z += delta.z;\n"
"        \n"
"        vel.x = invStepSize * delta.x;\n"
"        vel.y = invStepSize * delta.y;\n"
"        vel.z = invStepSize * delta.z;\n"
"        \n"
"        posq[idx] = pos;\n"
"        velm[idx] = vel;\n"
"    }\n"
"}\n"
"\n"
"// \n"
"// Hard Wall Constraints: Prevent Drude-Parent Distance Exceeding Maximum\n"
"// \n"
"\n"
"extern \"C\" __global__ void applyHardWallConstraints(\n"
"    float4* __restrict__ posq,\n"
"    float4* __restrict__ velm,\n"
"    const int2* __restrict__ pairParticles,\n"
"    const float2* __restrict__ stepSizeBuffer,\n"
"    float maxDrudeDistance,\n"
"    float hardwallscaleDrude,\n"
"    int numPairs)\n"
"{\n"
"    float stepSize = stepSizeBuffer[0].y;\n"
"    \n"
"    int idx = blockIdx.x * blockDim.x + threadIdx.x;\n"
"    if (idx >= numPairs) return;\n"
"    \n"
"    int2 particles = pairParticles[idx];\n"
"    float4 pos1 = posq[particles.x];\n"
"    float4 pos2 = posq[particles.y];\n"
"    \n"
"    float dx = pos1.x - pos2.x;\n"
"    float dy = pos1.y - pos2.y;\n"
"    float dz = pos1.z - pos2.z;\n"
"    float r = sqrtf(dx*dx + dy*dy + dz*dz);\n"
"    float rInv = 1.0f / r;\n"
"    \n"
"    if (rInv * maxDrudeDistance < 1.0f) {\n"
"        // Constraint violated - \"bounce\" off hard wall\n"
"        float3 bondDir = make_float3(dx*rInv, dy*rInv, dz*rInv);\n"
"        float4 vel1 = velm[particles.x];\n"
"        float4 vel2 = velm[particles.y];\n"
"        float mass1 = 1.0f / vel1.w;\n"
"        float mass2 = 1.0f / vel2.w;\n"
"        float deltaR = r - maxDrudeDistance;\n"
"        float deltaT = stepSize;\n"
"        \n"
"        float dotvr1 = vel1.x*bondDir.x + vel1.y*bondDir.y + vel1.z*bondDir.z;\n"
"        float3 vb1 = make_float3(bondDir.x*dotvr1, bondDir.y*dotvr1, bondDir.z*dotvr1);\n"
"        float3 vp1 = make_float3(vel1.x - vb1.x, vel1.y - vb1.y, vel1.z - vb1.z);\n"
"        \n"
"        if (vel2.w == 0.0f) {\n"
"            // Parent is massless - move only Drude particle\n"
"            if (dotvr1 != 0.0f)\n"
"                deltaT = deltaR / fabsf(dotvr1);\n"
"            if (deltaT > stepSize)\n"
"                deltaT = stepSize;\n"
"            dotvr1 = -dotvr1 * hardwallscaleDrude / (fabsf(dotvr1) * sqrtf(mass1));\n"
"            float dr = -deltaR + deltaT * dotvr1;\n"
"            pos1.x += bondDir.x * dr;\n"
"            pos1.y += bondDir.y * dr;\n"
"            pos1.z += bondDir.z * dr;\n"
"            posq[particles.x] = pos1;\n"
"            vel1.x = vp1.x + bondDir.x * dotvr1;\n"
"            vel1.y = vp1.y + bondDir.y * dotvr1;\n"
"            vel1.z = vp1.z + bondDir.z * dotvr1;\n"
"            velm[particles.x] = vel1;\n"
"        }\n"
"        else {\n"
"            // Both particles have mass - move both\n"
"            float invTotalMass = 1.0f / (mass1 + mass2);\n"
"            float dotvr2 = vel2.x*bondDir.x + vel2.y*bondDir.y + vel2.z*bondDir.z;\n"
"            float3 vb2 = make_float3(bondDir.x*dotvr2, bondDir.y*dotvr2, bondDir.z*dotvr2);\n"
"            float3 vp2 = make_float3(vel2.x - vb2.x, vel2.y - vb2.y, vel2.z - vb2.z);\n"
"            float vbCMass = (mass1*dotvr1 + mass2*dotvr2) * invTotalMass;\n"
"            dotvr1 -= vbCMass;\n"
"            dotvr2 -= vbCMass;\n"
"            if (dotvr1 != dotvr2)\n"
"                deltaT = deltaR / fabsf(dotvr1 - dotvr2);\n"
"            if (deltaT > stepSize)\n"
"                deltaT = stepSize;\n"
"            float vBond = hardwallscaleDrude / sqrtf(mass1);\n"
"            dotvr1 = -dotvr1 * vBond * mass2 * invTotalMass / fabsf(dotvr1);\n"
"            dotvr2 = -dotvr2 * vBond * mass1 * invTotalMass / fabsf(dotvr2);\n"
"            float dr1 = -deltaR * mass2 * invTotalMass + deltaT * dotvr1;\n"
"            float dr2 = deltaR * mass1 * invTotalMass + deltaT * dotvr2;\n"
"            dotvr1 += vbCMass;\n"
"            dotvr2 += vbCMass;\n"
"            pos1.x += bondDir.x * dr1;\n"
"            pos1.y += bondDir.y * dr1;\n"
"            pos1.z += bondDir.z * dr1;\n"
"            pos2.x += bondDir.x * dr2;\n"
"            pos2.y += bondDir.y * dr2;\n"
"            pos2.z += bondDir.z * dr2;\n"
"            posq[particles.x] = pos1;\n"
"            posq[particles.y] = pos2;\n"
"            vel1.x = vp1.x + bondDir.x * dotvr1;\n"
"            vel1.y = vp1.y + bondDir.y * dotvr1;\n"
"            vel1.z = vp1.z + bondDir.z * dotvr1;\n"
"            vel2.x = vp2.x + bondDir.x * dotvr2;\n"
"            vel2.y = vp2.y + bondDir.y * dotvr2;\n"
"            vel2.z = vp2.z + bondDir.z * dotvr2;\n"
"            velm[particles.x] = vel1;\n"
"            velm[particles.y] = vel2;\n"
"        }\n"
"    }\n"
"}\n"
"";
