# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.4.0
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if getattr(globals().get("__spec__"), "parent", None) or __package__ or "." in __name__:
    from . import _constantvoltage
else:
    import _constantvoltage

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


import weakref

class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _constantvoltage.delete_SwigPyIterator

    def value(self):
        return _constantvoltage.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _constantvoltage.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _constantvoltage.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _constantvoltage.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _constantvoltage.SwigPyIterator_equal(self, x)

    def copy(self):
        return _constantvoltage.SwigPyIterator_copy(self)

    def next(self):
        return _constantvoltage.SwigPyIterator_next(self)

    def __next__(self):
        return _constantvoltage.SwigPyIterator___next__(self)

    def previous(self):
        return _constantvoltage.SwigPyIterator_previous(self)

    def advance(self, n):
        return _constantvoltage.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _constantvoltage.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _constantvoltage.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _constantvoltage.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _constantvoltage.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _constantvoltage.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _constantvoltage.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _constantvoltage:
_constantvoltage.SwigPyIterator_swigregister(SwigPyIterator)
class vectord(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _constantvoltage.vectord_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _constantvoltage.vectord___nonzero__(self)

    def __bool__(self):
        return _constantvoltage.vectord___bool__(self)

    def __len__(self):
        return _constantvoltage.vectord___len__(self)

    def __getslice__(self, i, j):
        return _constantvoltage.vectord___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _constantvoltage.vectord___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _constantvoltage.vectord___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _constantvoltage.vectord___delitem__(self, *args)

    def __getitem__(self, *args):
        return _constantvoltage.vectord___getitem__(self, *args)

    def __setitem__(self, *args):
        return _constantvoltage.vectord___setitem__(self, *args)

    def pop(self):
        return _constantvoltage.vectord_pop(self)

    def append(self, x):
        return _constantvoltage.vectord_append(self, x)

    def empty(self):
        return _constantvoltage.vectord_empty(self)

    def size(self):
        return _constantvoltage.vectord_size(self)

    def swap(self, v):
        return _constantvoltage.vectord_swap(self, v)

    def begin(self):
        return _constantvoltage.vectord_begin(self)

    def end(self):
        return _constantvoltage.vectord_end(self)

    def rbegin(self):
        return _constantvoltage.vectord_rbegin(self)

    def rend(self):
        return _constantvoltage.vectord_rend(self)

    def clear(self):
        return _constantvoltage.vectord_clear(self)

    def get_allocator(self):
        return _constantvoltage.vectord_get_allocator(self)

    def pop_back(self):
        return _constantvoltage.vectord_pop_back(self)

    def erase(self, *args):
        return _constantvoltage.vectord_erase(self, *args)

    def __init__(self, *args):
        _constantvoltage.vectord_swiginit(self, _constantvoltage.new_vectord(*args))

    def push_back(self, x):
        return _constantvoltage.vectord_push_back(self, x)

    def front(self):
        return _constantvoltage.vectord_front(self)

    def back(self):
        return _constantvoltage.vectord_back(self)

    def assign(self, n, x):
        return _constantvoltage.vectord_assign(self, n, x)

    def resize(self, *args):
        return _constantvoltage.vectord_resize(self, *args)

    def insert(self, *args):
        return _constantvoltage.vectord_insert(self, *args)

    def reserve(self, n):
        return _constantvoltage.vectord_reserve(self, n)

    def capacity(self):
        return _constantvoltage.vectord_capacity(self)
    __swig_destroy__ = _constantvoltage.delete_vectord

# Register vectord in _constantvoltage:
_constantvoltage.vectord_swigregister(vectord)
class vectori(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _constantvoltage.vectori_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _constantvoltage.vectori___nonzero__(self)

    def __bool__(self):
        return _constantvoltage.vectori___bool__(self)

    def __len__(self):
        return _constantvoltage.vectori___len__(self)

    def __getslice__(self, i, j):
        return _constantvoltage.vectori___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _constantvoltage.vectori___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _constantvoltage.vectori___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _constantvoltage.vectori___delitem__(self, *args)

    def __getitem__(self, *args):
        return _constantvoltage.vectori___getitem__(self, *args)

    def __setitem__(self, *args):
        return _constantvoltage.vectori___setitem__(self, *args)

    def pop(self):
        return _constantvoltage.vectori_pop(self)

    def append(self, x):
        return _constantvoltage.vectori_append(self, x)

    def empty(self):
        return _constantvoltage.vectori_empty(self)

    def size(self):
        return _constantvoltage.vectori_size(self)

    def swap(self, v):
        return _constantvoltage.vectori_swap(self, v)

    def begin(self):
        return _constantvoltage.vectori_begin(self)

    def end(self):
        return _constantvoltage.vectori_end(self)

    def rbegin(self):
        return _constantvoltage.vectori_rbegin(self)

    def rend(self):
        return _constantvoltage.vectori_rend(self)

    def clear(self):
        return _constantvoltage.vectori_clear(self)

    def get_allocator(self):
        return _constantvoltage.vectori_get_allocator(self)

    def pop_back(self):
        return _constantvoltage.vectori_pop_back(self)

    def erase(self, *args):
        return _constantvoltage.vectori_erase(self, *args)

    def __init__(self, *args):
        _constantvoltage.vectori_swiginit(self, _constantvoltage.new_vectori(*args))

    def push_back(self, x):
        return _constantvoltage.vectori_push_back(self, x)

    def front(self):
        return _constantvoltage.vectori_front(self)

    def back(self):
        return _constantvoltage.vectori_back(self)

    def assign(self, n, x):
        return _constantvoltage.vectori_assign(self, n, x)

    def resize(self, *args):
        return _constantvoltage.vectori_resize(self, *args)

    def insert(self, *args):
        return _constantvoltage.vectori_insert(self, *args)

    def reserve(self, n):
        return _constantvoltage.vectori_reserve(self, n)

    def capacity(self):
        return _constantvoltage.vectori_capacity(self)
    __swig_destroy__ = _constantvoltage.delete_vectori

# Register vectori in _constantvoltage:
_constantvoltage.vectori_swigregister(vectori)
class ConstantVoltageForce(object):
    r"""Proxy of C++ OpenMM::ConstantVoltageForce class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        r"""__init__(self) -> ConstantVoltageForce"""
        _constantvoltage.ConstantVoltageForce_swiginit(self, _constantvoltage.new_ConstantVoltageForce())

    def addCathodeAtom(self, particle, area):
        r"""addCathodeAtom(self, particle, area) -> int"""
        return _constantvoltage.ConstantVoltageForce_addCathodeAtom(self, particle, area)

    def getNumCathodeAtoms(self):
        r"""getNumCathodeAtoms(self) -> int"""
        return _constantvoltage.ConstantVoltageForce_getNumCathodeAtoms(self)

    def getCathodeAtomParameters(self, index):
        r"""getCathodeAtomParameters(self, index)"""
        return _constantvoltage.ConstantVoltageForce_getCathodeAtomParameters(self, index)

    def setCathodeAtomParameters(self, index, particle, area):
        r"""setCathodeAtomParameters(self, index, particle, area)"""
        return _constantvoltage.ConstantVoltageForce_setCathodeAtomParameters(self, index, particle, area)

    def addAnodeAtom(self, particle, area):
        r"""addAnodeAtom(self, particle, area) -> int"""
        return _constantvoltage.ConstantVoltageForce_addAnodeAtom(self, particle, area)

    def getNumAnodeAtoms(self):
        r"""getNumAnodeAtoms(self) -> int"""
        return _constantvoltage.ConstantVoltageForce_getNumAnodeAtoms(self)

    def getAnodeAtomParameters(self, index):
        r"""getAnodeAtomParameters(self, index)"""
        return _constantvoltage.ConstantVoltageForce_getAnodeAtomParameters(self, index)

    def setAnodeAtomParameters(self, index, particle, area):
        r"""setAnodeAtomParameters(self, index, particle, area)"""
        return _constantvoltage.ConstantVoltageForce_setAnodeAtomParameters(self, index, particle, area)

    def addElectrolyteAtom(self, particle):
        r"""addElectrolyteAtom(self, particle) -> int"""
        return _constantvoltage.ConstantVoltageForce_addElectrolyteAtom(self, particle)

    def getNumElectrolyteAtoms(self):
        r"""getNumElectrolyteAtoms(self) -> int"""
        return _constantvoltage.ConstantVoltageForce_getNumElectrolyteAtoms(self)

    def getElectrolyteAtomParticle(self, index):
        r"""getElectrolyteAtomParticle(self, index) -> int"""
        return _constantvoltage.ConstantVoltageForce_getElectrolyteAtomParticle(self, index)

    def setVoltage(self, voltage):
        r"""setVoltage(self, voltage)"""
        return _constantvoltage.ConstantVoltageForce_setVoltage(self, voltage)

    def getVoltage(self):
        r"""getVoltage(self) -> double"""
        return _constantvoltage.ConstantVoltageForce_getVoltage(self)

    def setLgap(self, lgap):
        r"""setLgap(self, lgap)"""
        return _constantvoltage.ConstantVoltageForce_setLgap(self, lgap)

    def getLgap(self):
        r"""getLgap(self) -> double"""
        return _constantvoltage.ConstantVoltageForce_getLgap(self)

    def setLcell(self, lcell):
        r"""setLcell(self, lcell)"""
        return _constantvoltage.ConstantVoltageForce_setLcell(self, lcell)

    def getLcell(self):
        r"""getLcell(self) -> double"""
        return _constantvoltage.ConstantVoltageForce_getLcell(self)

    def setTotalArea(self, area):
        r"""setTotalArea(self, area)"""
        return _constantvoltage.ConstantVoltageForce_setTotalArea(self, area)

    def getTotalArea(self):
        r"""getTotalArea(self) -> double"""
        return _constantvoltage.ConstantVoltageForce_getTotalArea(self)

    def setElectrodeZPositions(self, zCathode, zAnode):
        r"""setElectrodeZPositions(self, zCathode, zAnode)"""
        return _constantvoltage.ConstantVoltageForce_setElectrodeZPositions(self, zCathode, zAnode)

    def getZCathode(self):
        r"""getZCathode(self) -> double"""
        return _constantvoltage.ConstantVoltageForce_getZCathode(self)

    def getZAnode(self):
        r"""getZAnode(self) -> double"""
        return _constantvoltage.ConstantVoltageForce_getZAnode(self)

    def setNumSCFIterations(self, n):
        r"""setNumSCFIterations(self, n)"""
        return _constantvoltage.ConstantVoltageForce_setNumSCFIterations(self, n)

    def getNumSCFIterations(self):
        r"""getNumSCFIterations(self) -> int"""
        return _constantvoltage.ConstantVoltageForce_getNumSCFIterations(self)

    def setSCFFrequency(self, freq):
        r"""setSCFFrequency(self, freq)"""
        return _constantvoltage.ConstantVoltageForce_setSCFFrequency(self, freq)

    def getSCFFrequency(self):
        r"""getSCFFrequency(self) -> int"""
        return _constantvoltage.ConstantVoltageForce_getSCFFrequency(self)

    def setSmallThreshold(self, threshold):
        r"""setSmallThreshold(self, threshold)"""
        return _constantvoltage.ConstantVoltageForce_setSmallThreshold(self, threshold)

    def getSmallThreshold(self):
        r"""getSmallThreshold(self) -> double"""
        return _constantvoltage.ConstantVoltageForce_getSmallThreshold(self)

    def usesPeriodicBoundaryConditions(self):
        r"""usesPeriodicBoundaryConditions(self) -> bool"""
        return _constantvoltage.ConstantVoltageForce_usesPeriodicBoundaryConditions(self)
    __swig_destroy__ = _constantvoltage.delete_ConstantVoltageForce

# Register ConstantVoltageForce in _constantvoltage:
_constantvoltage.ConstantVoltageForce_swigregister(ConstantVoltageForce)
class ConstantVDrudeLangevinIntegrator(object):
    r"""Proxy of C++ OpenMM::ConstantVDrudeLangevinIntegrator class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, temperature, frictionCoeff, drudeTemperature, drudeFriction, stepSize):
        r"""__init__(self, temperature, frictionCoeff, drudeTemperature, drudeFriction, stepSize) -> ConstantVDrudeLangevinIntegrator"""
        _constantvoltage.ConstantVDrudeLangevinIntegrator_swiginit(self, _constantvoltage.new_ConstantVDrudeLangevinIntegrator(temperature, frictionCoeff, drudeTemperature, drudeFriction, stepSize))

    def getTemperature(self):
        r"""getTemperature(self) -> double"""
        return _constantvoltage.ConstantVDrudeLangevinIntegrator_getTemperature(self)

    def setTemperature(self, temp):
        r"""setTemperature(self, temp)"""
        return _constantvoltage.ConstantVDrudeLangevinIntegrator_setTemperature(self, temp)

    def getFriction(self):
        r"""getFriction(self) -> double"""
        return _constantvoltage.ConstantVDrudeLangevinIntegrator_getFriction(self)

    def setFriction(self, coeff):
        r"""setFriction(self, coeff)"""
        return _constantvoltage.ConstantVDrudeLangevinIntegrator_setFriction(self, coeff)

    def getDrudeTemperature(self):
        r"""getDrudeTemperature(self) -> double"""
        return _constantvoltage.ConstantVDrudeLangevinIntegrator_getDrudeTemperature(self)

    def setDrudeTemperature(self, temp):
        r"""setDrudeTemperature(self, temp)"""
        return _constantvoltage.ConstantVDrudeLangevinIntegrator_setDrudeTemperature(self, temp)

    def getDrudeFriction(self):
        r"""getDrudeFriction(self) -> double"""
        return _constantvoltage.ConstantVDrudeLangevinIntegrator_getDrudeFriction(self)

    def setDrudeFriction(self, coeff):
        r"""setDrudeFriction(self, coeff)"""
        return _constantvoltage.ConstantVDrudeLangevinIntegrator_setDrudeFriction(self, coeff)

    def getMaxDrudeDistance(self):
        r"""getMaxDrudeDistance(self) -> double"""
        return _constantvoltage.ConstantVDrudeLangevinIntegrator_getMaxDrudeDistance(self)

    def setMaxDrudeDistance(self, distance):
        r"""setMaxDrudeDistance(self, distance)"""
        return _constantvoltage.ConstantVDrudeLangevinIntegrator_setMaxDrudeDistance(self, distance)

    def getRandomNumberSeed(self):
        r"""getRandomNumberSeed(self) -> int"""
        return _constantvoltage.ConstantVDrudeLangevinIntegrator_getRandomNumberSeed(self)

    def setRandomNumberSeed(self, seed):
        r"""setRandomNumberSeed(self, seed)"""
        return _constantvoltage.ConstantVDrudeLangevinIntegrator_setRandomNumberSeed(self, seed)

    def step(self, steps):
        r"""step(self, steps)"""
        return _constantvoltage.ConstantVDrudeLangevinIntegrator_step(self, steps)
    __swig_destroy__ = _constantvoltage.delete_ConstantVDrudeLangevinIntegrator

# Register ConstantVDrudeLangevinIntegrator in _constantvoltage:
_constantvoltage.ConstantVDrudeLangevinIntegrator_swigregister(ConstantVDrudeLangevinIntegrator)

__all__ = ['ConstantVoltageForce', 'ConstantVDrudeLangevinIntegrator']


