# CMake generated Testfile for 
# Source directory: /home/andy/test_optimization/openmm-8.4.0/platforms/cpu/tests
# Build directory: /home/andy/test_optimization/openmm-8.4.0/build_test/platforms/cpu/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(TestCpuCheckpoints "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCpuCheckpoints" "single")
set_tests_properties(TestCpuCheckpoints PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cpu/tests/CMakeLists.txt;38;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cpu/tests/CMakeLists.txt;0;")
add_test(TestCpuCompoundIntegrator "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCpuCompoundIntegrator" "single")
set_tests_properties(TestCpuCompoundIntegrator PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cpu/tests/CMakeLists.txt;38;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cpu/tests/CMakeLists.txt;0;")
add_test(TestCpuConstantPotentialForce "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCpuConstantPotentialForce" "single")
set_tests_properties(TestCpuConstantPotentialForce PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cpu/tests/CMakeLists.txt;38;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cpu/tests/CMakeLists.txt;0;")
add_test(TestCpuCustomCPPForce "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCpuCustomCPPForce" "single")
set_tests_properties(TestCpuCustomCPPForce PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cpu/tests/CMakeLists.txt;38;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cpu/tests/CMakeLists.txt;0;")
add_test(TestCpuCustomGBForce "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCpuCustomGBForce" "single")
set_tests_properties(TestCpuCustomGBForce PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cpu/tests/CMakeLists.txt;38;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cpu/tests/CMakeLists.txt;0;")
add_test(TestCpuCustomManyParticleForce "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCpuCustomManyParticleForce" "single")
set_tests_properties(TestCpuCustomManyParticleForce PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cpu/tests/CMakeLists.txt;38;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cpu/tests/CMakeLists.txt;0;")
add_test(TestCpuCustomNonbondedForce "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCpuCustomNonbondedForce" "single")
set_tests_properties(TestCpuCustomNonbondedForce PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cpu/tests/CMakeLists.txt;38;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cpu/tests/CMakeLists.txt;0;")
add_test(TestCpuDispersionPME "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCpuDispersionPME" "single")
set_tests_properties(TestCpuDispersionPME PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cpu/tests/CMakeLists.txt;38;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cpu/tests/CMakeLists.txt;0;")
add_test(TestCpuEwald "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCpuEwald" "single")
set_tests_properties(TestCpuEwald PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cpu/tests/CMakeLists.txt;38;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cpu/tests/CMakeLists.txt;0;")
add_test(TestCpuGBSAOBCForce "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCpuGBSAOBCForce" "single")
set_tests_properties(TestCpuGBSAOBCForce PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cpu/tests/CMakeLists.txt;38;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cpu/tests/CMakeLists.txt;0;")
add_test(TestCpuGayBerneForce "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCpuGayBerneForce" "single")
set_tests_properties(TestCpuGayBerneForce PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cpu/tests/CMakeLists.txt;38;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cpu/tests/CMakeLists.txt;0;")
add_test(TestCpuHarmonicAngleForce "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCpuHarmonicAngleForce" "single")
set_tests_properties(TestCpuHarmonicAngleForce PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cpu/tests/CMakeLists.txt;38;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cpu/tests/CMakeLists.txt;0;")
add_test(TestCpuLangevinIntegrator "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCpuLangevinIntegrator" "single")
set_tests_properties(TestCpuLangevinIntegrator PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cpu/tests/CMakeLists.txt;38;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cpu/tests/CMakeLists.txt;0;")
add_test(TestCpuLangevinMiddleIntegrator "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCpuLangevinMiddleIntegrator" "single")
set_tests_properties(TestCpuLangevinMiddleIntegrator PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cpu/tests/CMakeLists.txt;38;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cpu/tests/CMakeLists.txt;0;")
add_test(TestCpuNeighborList "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCpuNeighborList" "single")
set_tests_properties(TestCpuNeighborList PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cpu/tests/CMakeLists.txt;38;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cpu/tests/CMakeLists.txt;0;")
add_test(TestCpuNonbondedForce "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCpuNonbondedForce" "single")
set_tests_properties(TestCpuNonbondedForce PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cpu/tests/CMakeLists.txt;38;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cpu/tests/CMakeLists.txt;0;")
add_test(TestCpuPeriodicTorsionForce "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCpuPeriodicTorsionForce" "single")
set_tests_properties(TestCpuPeriodicTorsionForce PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cpu/tests/CMakeLists.txt;38;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cpu/tests/CMakeLists.txt;0;")
add_test(TestCpuRBTorsionForce "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCpuRBTorsionForce" "single")
set_tests_properties(TestCpuRBTorsionForce PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cpu/tests/CMakeLists.txt;38;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cpu/tests/CMakeLists.txt;0;")
add_test(TestCpuSettle "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCpuSettle" "single")
set_tests_properties(TestCpuSettle PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cpu/tests/CMakeLists.txt;38;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cpu/tests/CMakeLists.txt;0;")
