# CMake generated Testfile for 
# Source directory: /home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests
# Build directory: /home/andy/test_optimization/openmm-8.4.0/build_test/platforms/cuda/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(TestCudaATMForceSingle "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaATMForce" "single")
set_tests_properties(TestCudaATMForceSingle PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;33;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaATMForceMixed "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaATMForce" "mixed")
set_tests_properties(TestCudaATMForceMixed PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;35;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaATMForceDouble "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaATMForce" "double")
set_tests_properties(TestCudaATMForceDouble PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;36;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaAndersenThermostatSingle "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaAndersenThermostat" "single")
set_tests_properties(TestCudaAndersenThermostatSingle PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;33;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaAndersenThermostatMixed "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaAndersenThermostat" "mixed")
set_tests_properties(TestCudaAndersenThermostatMixed PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;35;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaAndersenThermostatDouble "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaAndersenThermostat" "double")
set_tests_properties(TestCudaAndersenThermostatDouble PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;36;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaBrownianIntegratorSingle "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaBrownianIntegrator" "single")
set_tests_properties(TestCudaBrownianIntegratorSingle PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;33;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaBrownianIntegratorMixed "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaBrownianIntegrator" "mixed")
set_tests_properties(TestCudaBrownianIntegratorMixed PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;35;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaBrownianIntegratorDouble "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaBrownianIntegrator" "double")
set_tests_properties(TestCudaBrownianIntegratorDouble PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;36;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaCMAPTorsionForceSingle "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaCMAPTorsionForce" "single")
set_tests_properties(TestCudaCMAPTorsionForceSingle PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;33;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaCMAPTorsionForceMixed "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaCMAPTorsionForce" "mixed")
set_tests_properties(TestCudaCMAPTorsionForceMixed PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;35;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaCMAPTorsionForceDouble "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaCMAPTorsionForce" "double")
set_tests_properties(TestCudaCMAPTorsionForceDouble PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;36;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaCMMotionRemoverSingle "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaCMMotionRemover" "single")
set_tests_properties(TestCudaCMMotionRemoverSingle PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;33;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaCMMotionRemoverMixed "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaCMMotionRemover" "mixed")
set_tests_properties(TestCudaCMMotionRemoverMixed PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;35;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaCMMotionRemoverDouble "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaCMMotionRemover" "double")
set_tests_properties(TestCudaCMMotionRemoverDouble PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;36;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaCheckpointsSingle "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaCheckpoints" "single")
set_tests_properties(TestCudaCheckpointsSingle PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;33;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaCheckpointsMixed "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaCheckpoints" "mixed")
set_tests_properties(TestCudaCheckpointsMixed PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;35;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaCheckpointsDouble "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaCheckpoints" "double")
set_tests_properties(TestCudaCheckpointsDouble PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;36;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaCompoundIntegratorSingle "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaCompoundIntegrator" "single")
set_tests_properties(TestCudaCompoundIntegratorSingle PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;33;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaCompoundIntegratorMixed "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaCompoundIntegrator" "mixed")
set_tests_properties(TestCudaCompoundIntegratorMixed PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;35;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaCompoundIntegratorDouble "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaCompoundIntegrator" "double")
set_tests_properties(TestCudaCompoundIntegratorDouble PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;36;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaConstantPotentialForceSingle "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaConstantPotentialForce" "single")
set_tests_properties(TestCudaConstantPotentialForceSingle PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;33;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaConstantPotentialForceMixed "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaConstantPotentialForce" "mixed")
set_tests_properties(TestCudaConstantPotentialForceMixed PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;35;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaConstantPotentialForceDouble "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaConstantPotentialForce" "double")
set_tests_properties(TestCudaConstantPotentialForceDouble PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;36;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaCustomAngleForceSingle "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaCustomAngleForce" "single")
set_tests_properties(TestCudaCustomAngleForceSingle PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;33;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaCustomAngleForceMixed "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaCustomAngleForce" "mixed")
set_tests_properties(TestCudaCustomAngleForceMixed PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;35;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaCustomAngleForceDouble "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaCustomAngleForce" "double")
set_tests_properties(TestCudaCustomAngleForceDouble PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;36;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaCustomBondForceSingle "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaCustomBondForce" "single")
set_tests_properties(TestCudaCustomBondForceSingle PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;33;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaCustomBondForceMixed "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaCustomBondForce" "mixed")
set_tests_properties(TestCudaCustomBondForceMixed PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;35;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaCustomBondForceDouble "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaCustomBondForce" "double")
set_tests_properties(TestCudaCustomBondForceDouble PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;36;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaCustomCPPForceSingle "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaCustomCPPForce" "single")
set_tests_properties(TestCudaCustomCPPForceSingle PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;33;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaCustomCPPForceMixed "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaCustomCPPForce" "mixed")
set_tests_properties(TestCudaCustomCPPForceMixed PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;35;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaCustomCPPForceDouble "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaCustomCPPForce" "double")
set_tests_properties(TestCudaCustomCPPForceDouble PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;36;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaCustomCVForceSingle "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaCustomCVForce" "single")
set_tests_properties(TestCudaCustomCVForceSingle PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;33;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaCustomCVForceMixed "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaCustomCVForce" "mixed")
set_tests_properties(TestCudaCustomCVForceMixed PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;35;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaCustomCVForceDouble "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaCustomCVForce" "double")
set_tests_properties(TestCudaCustomCVForceDouble PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;36;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaCustomCentroidBondForceSingle "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaCustomCentroidBondForce" "single")
set_tests_properties(TestCudaCustomCentroidBondForceSingle PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;33;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaCustomCentroidBondForceMixed "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaCustomCentroidBondForce" "mixed")
set_tests_properties(TestCudaCustomCentroidBondForceMixed PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;35;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaCustomCentroidBondForceDouble "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaCustomCentroidBondForce" "double")
set_tests_properties(TestCudaCustomCentroidBondForceDouble PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;36;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaCustomCompoundBondForceSingle "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaCustomCompoundBondForce" "single")
set_tests_properties(TestCudaCustomCompoundBondForceSingle PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;33;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaCustomCompoundBondForceMixed "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaCustomCompoundBondForce" "mixed")
set_tests_properties(TestCudaCustomCompoundBondForceMixed PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;35;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaCustomCompoundBondForceDouble "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaCustomCompoundBondForce" "double")
set_tests_properties(TestCudaCustomCompoundBondForceDouble PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;36;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaCustomExternalForceSingle "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaCustomExternalForce" "single")
set_tests_properties(TestCudaCustomExternalForceSingle PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;33;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaCustomExternalForceMixed "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaCustomExternalForce" "mixed")
set_tests_properties(TestCudaCustomExternalForceMixed PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;35;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaCustomExternalForceDouble "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaCustomExternalForce" "double")
set_tests_properties(TestCudaCustomExternalForceDouble PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;36;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaCustomGBForceSingle "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaCustomGBForce" "single")
set_tests_properties(TestCudaCustomGBForceSingle PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;33;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaCustomGBForceMixed "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaCustomGBForce" "mixed")
set_tests_properties(TestCudaCustomGBForceMixed PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;35;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaCustomGBForceDouble "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaCustomGBForce" "double")
set_tests_properties(TestCudaCustomGBForceDouble PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;36;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaCustomHbondForceSingle "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaCustomHbondForce" "single")
set_tests_properties(TestCudaCustomHbondForceSingle PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;33;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaCustomHbondForceMixed "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaCustomHbondForce" "mixed")
set_tests_properties(TestCudaCustomHbondForceMixed PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;35;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaCustomHbondForceDouble "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaCustomHbondForce" "double")
set_tests_properties(TestCudaCustomHbondForceDouble PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;36;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaCustomIntegratorSingle "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaCustomIntegrator" "single")
set_tests_properties(TestCudaCustomIntegratorSingle PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;33;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaCustomIntegratorMixed "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaCustomIntegrator" "mixed")
set_tests_properties(TestCudaCustomIntegratorMixed PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;35;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaCustomIntegratorDouble "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaCustomIntegrator" "double")
set_tests_properties(TestCudaCustomIntegratorDouble PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;36;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaCustomManyParticleForceSingle "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaCustomManyParticleForce" "single")
set_tests_properties(TestCudaCustomManyParticleForceSingle PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;33;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaCustomManyParticleForceMixed "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaCustomManyParticleForce" "mixed")
set_tests_properties(TestCudaCustomManyParticleForceMixed PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;35;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaCustomManyParticleForceDouble "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaCustomManyParticleForce" "double")
set_tests_properties(TestCudaCustomManyParticleForceDouble PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;36;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaCustomNonbondedForceSingle "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaCustomNonbondedForce" "single")
set_tests_properties(TestCudaCustomNonbondedForceSingle PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;33;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaCustomNonbondedForceMixed "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaCustomNonbondedForce" "mixed")
set_tests_properties(TestCudaCustomNonbondedForceMixed PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;35;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaCustomNonbondedForceDouble "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaCustomNonbondedForce" "double")
set_tests_properties(TestCudaCustomNonbondedForceDouble PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;36;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaCustomTorsionForceSingle "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaCustomTorsionForce" "single")
set_tests_properties(TestCudaCustomTorsionForceSingle PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;33;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaCustomTorsionForceMixed "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaCustomTorsionForce" "mixed")
set_tests_properties(TestCudaCustomTorsionForceMixed PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;35;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaCustomTorsionForceDouble "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaCustomTorsionForce" "double")
set_tests_properties(TestCudaCustomTorsionForceDouble PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;36;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaDPDIntegratorSingle "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaDPDIntegrator" "single")
set_tests_properties(TestCudaDPDIntegratorSingle PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;33;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaDPDIntegratorMixed "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaDPDIntegrator" "mixed")
set_tests_properties(TestCudaDPDIntegratorMixed PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;35;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaDPDIntegratorDouble "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaDPDIntegrator" "double")
set_tests_properties(TestCudaDPDIntegratorDouble PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;36;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaDispersionPMESingle "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaDispersionPME" "single")
set_tests_properties(TestCudaDispersionPMESingle PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;33;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaDispersionPMEMixed "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaDispersionPME" "mixed")
set_tests_properties(TestCudaDispersionPMEMixed PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;35;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaDispersionPMEDouble "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaDispersionPME" "double")
set_tests_properties(TestCudaDispersionPMEDouble PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;36;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaEwaldSingle "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaEwald" "single")
set_tests_properties(TestCudaEwaldSingle PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;33;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaEwaldMixed "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaEwald" "mixed")
set_tests_properties(TestCudaEwaldMixed PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;35;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaEwaldDouble "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaEwald" "double")
set_tests_properties(TestCudaEwaldDouble PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;36;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaFFT3DSingle "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaFFT3D" "single")
set_tests_properties(TestCudaFFT3DSingle PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;33;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaFFT3DMixed "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaFFT3D" "mixed")
set_tests_properties(TestCudaFFT3DMixed PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;35;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaFFT3DDouble "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaFFT3D" "double")
set_tests_properties(TestCudaFFT3DDouble PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;36;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaGBSAOBCForceSingle "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaGBSAOBCForce" "single")
set_tests_properties(TestCudaGBSAOBCForceSingle PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;33;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaGBSAOBCForceMixed "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaGBSAOBCForce" "mixed")
set_tests_properties(TestCudaGBSAOBCForceMixed PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;35;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaGBSAOBCForceDouble "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaGBSAOBCForce" "double")
set_tests_properties(TestCudaGBSAOBCForceDouble PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;36;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaGayBerneForceSingle "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaGayBerneForce" "single")
set_tests_properties(TestCudaGayBerneForceSingle PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;33;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaGayBerneForceMixed "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaGayBerneForce" "mixed")
set_tests_properties(TestCudaGayBerneForceMixed PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;35;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaGayBerneForceDouble "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaGayBerneForce" "double")
set_tests_properties(TestCudaGayBerneForceDouble PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;36;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaHarmonicAngleForceSingle "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaHarmonicAngleForce" "single")
set_tests_properties(TestCudaHarmonicAngleForceSingle PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;33;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaHarmonicAngleForceMixed "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaHarmonicAngleForce" "mixed")
set_tests_properties(TestCudaHarmonicAngleForceMixed PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;35;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaHarmonicAngleForceDouble "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaHarmonicAngleForce" "double")
set_tests_properties(TestCudaHarmonicAngleForceDouble PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;36;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaHarmonicBondForceSingle "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaHarmonicBondForce" "single")
set_tests_properties(TestCudaHarmonicBondForceSingle PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;33;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaHarmonicBondForceMixed "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaHarmonicBondForce" "mixed")
set_tests_properties(TestCudaHarmonicBondForceMixed PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;35;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaHarmonicBondForceDouble "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaHarmonicBondForce" "double")
set_tests_properties(TestCudaHarmonicBondForceDouble PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;36;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaLangevinIntegratorSingle "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaLangevinIntegrator" "single")
set_tests_properties(TestCudaLangevinIntegratorSingle PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;33;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaLangevinIntegratorMixed "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaLangevinIntegrator" "mixed")
set_tests_properties(TestCudaLangevinIntegratorMixed PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;35;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaLangevinIntegratorDouble "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaLangevinIntegrator" "double")
set_tests_properties(TestCudaLangevinIntegratorDouble PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;36;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaLangevinMiddleIntegratorSingle "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaLangevinMiddleIntegrator" "single")
set_tests_properties(TestCudaLangevinMiddleIntegratorSingle PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;33;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaLangevinMiddleIntegratorMixed "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaLangevinMiddleIntegrator" "mixed")
set_tests_properties(TestCudaLangevinMiddleIntegratorMixed PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;35;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaLangevinMiddleIntegratorDouble "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaLangevinMiddleIntegrator" "double")
set_tests_properties(TestCudaLangevinMiddleIntegratorDouble PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;36;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaLocalEnergyMinimizerSingle "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaLocalEnergyMinimizer" "single")
set_tests_properties(TestCudaLocalEnergyMinimizerSingle PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;33;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaLocalEnergyMinimizerMixed "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaLocalEnergyMinimizer" "mixed")
set_tests_properties(TestCudaLocalEnergyMinimizerMixed PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;35;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaLocalEnergyMinimizerDouble "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaLocalEnergyMinimizer" "double")
set_tests_properties(TestCudaLocalEnergyMinimizerDouble PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;36;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaMonteCarloAnisotropicBarostatSingle "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaMonteCarloAnisotropicBarostat" "single")
set_tests_properties(TestCudaMonteCarloAnisotropicBarostatSingle PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;33;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaMonteCarloAnisotropicBarostatMixed "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaMonteCarloAnisotropicBarostat" "mixed")
set_tests_properties(TestCudaMonteCarloAnisotropicBarostatMixed PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;35;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaMonteCarloAnisotropicBarostatDouble "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaMonteCarloAnisotropicBarostat" "double")
set_tests_properties(TestCudaMonteCarloAnisotropicBarostatDouble PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;36;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaMonteCarloBarostatSingle "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaMonteCarloBarostat" "single")
set_tests_properties(TestCudaMonteCarloBarostatSingle PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;33;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaMonteCarloBarostatMixed "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaMonteCarloBarostat" "mixed")
set_tests_properties(TestCudaMonteCarloBarostatMixed PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;35;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaMonteCarloBarostatDouble "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaMonteCarloBarostat" "double")
set_tests_properties(TestCudaMonteCarloBarostatDouble PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;36;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaMonteCarloFlexibleBarostatSingle "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaMonteCarloFlexibleBarostat" "single")
set_tests_properties(TestCudaMonteCarloFlexibleBarostatSingle PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;33;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaMonteCarloFlexibleBarostatMixed "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaMonteCarloFlexibleBarostat" "mixed")
set_tests_properties(TestCudaMonteCarloFlexibleBarostatMixed PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;35;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaMonteCarloFlexibleBarostatDouble "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaMonteCarloFlexibleBarostat" "double")
set_tests_properties(TestCudaMonteCarloFlexibleBarostatDouble PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;36;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaMultipleForcesSingle "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaMultipleForces" "single")
set_tests_properties(TestCudaMultipleForcesSingle PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;33;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaMultipleForcesMixed "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaMultipleForces" "mixed")
set_tests_properties(TestCudaMultipleForcesMixed PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;35;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaMultipleForcesDouble "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaMultipleForces" "double")
set_tests_properties(TestCudaMultipleForcesDouble PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;36;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaNonbondedForceSingle "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaNonbondedForce" "single")
set_tests_properties(TestCudaNonbondedForceSingle PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;33;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaNonbondedForceMixed "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaNonbondedForce" "mixed")
set_tests_properties(TestCudaNonbondedForceMixed PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;35;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaNonbondedForceDouble "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaNonbondedForce" "double")
set_tests_properties(TestCudaNonbondedForceDouble PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;36;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaNoseHooverIntegratorSingle "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaNoseHooverIntegrator" "single")
set_tests_properties(TestCudaNoseHooverIntegratorSingle PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;33;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaNoseHooverIntegratorMixed "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaNoseHooverIntegrator" "mixed")
set_tests_properties(TestCudaNoseHooverIntegratorMixed PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;35;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaNoseHooverIntegratorDouble "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaNoseHooverIntegrator" "double")
set_tests_properties(TestCudaNoseHooverIntegratorDouble PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;36;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaOrientationRestraintForceSingle "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaOrientationRestraintForce" "single")
set_tests_properties(TestCudaOrientationRestraintForceSingle PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;33;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaOrientationRestraintForceMixed "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaOrientationRestraintForce" "mixed")
set_tests_properties(TestCudaOrientationRestraintForceMixed PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;35;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaOrientationRestraintForceDouble "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaOrientationRestraintForce" "double")
set_tests_properties(TestCudaOrientationRestraintForceDouble PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;36;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaPeriodicTorsionForceSingle "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaPeriodicTorsionForce" "single")
set_tests_properties(TestCudaPeriodicTorsionForceSingle PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;33;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaPeriodicTorsionForceMixed "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaPeriodicTorsionForce" "mixed")
set_tests_properties(TestCudaPeriodicTorsionForceMixed PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;35;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaPeriodicTorsionForceDouble "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaPeriodicTorsionForce" "double")
set_tests_properties(TestCudaPeriodicTorsionForceDouble PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;36;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaQTBIntegratorSingle "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaQTBIntegrator" "single")
set_tests_properties(TestCudaQTBIntegratorSingle PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;33;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaQTBIntegratorMixed "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaQTBIntegrator" "mixed")
set_tests_properties(TestCudaQTBIntegratorMixed PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;35;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaQTBIntegratorDouble "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaQTBIntegrator" "double")
set_tests_properties(TestCudaQTBIntegratorDouble PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;36;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaRBTorsionForceSingle "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaRBTorsionForce" "single")
set_tests_properties(TestCudaRBTorsionForceSingle PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;33;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaRBTorsionForceMixed "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaRBTorsionForce" "mixed")
set_tests_properties(TestCudaRBTorsionForceMixed PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;35;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaRBTorsionForceDouble "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaRBTorsionForce" "double")
set_tests_properties(TestCudaRBTorsionForceDouble PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;36;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaRGForceSingle "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaRGForce" "single")
set_tests_properties(TestCudaRGForceSingle PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;33;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaRGForceMixed "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaRGForce" "mixed")
set_tests_properties(TestCudaRGForceMixed PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;35;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaRGForceDouble "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaRGForce" "double")
set_tests_properties(TestCudaRGForceDouble PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;36;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaRMSDForceSingle "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaRMSDForce" "single")
set_tests_properties(TestCudaRMSDForceSingle PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;33;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaRMSDForceMixed "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaRMSDForce" "mixed")
set_tests_properties(TestCudaRMSDForceMixed PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;35;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaRMSDForceDouble "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaRMSDForce" "double")
set_tests_properties(TestCudaRMSDForceDouble PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;36;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaRandomSingle "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaRandom" "single")
set_tests_properties(TestCudaRandomSingle PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;33;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaRandomMixed "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaRandom" "mixed")
set_tests_properties(TestCudaRandomMixed PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;35;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaRandomDouble "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaRandom" "double")
set_tests_properties(TestCudaRandomDouble PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;36;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaSettleSingle "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaSettle" "single")
set_tests_properties(TestCudaSettleSingle PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;33;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaSettleMixed "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaSettle" "mixed")
set_tests_properties(TestCudaSettleMixed PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;35;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaSettleDouble "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaSettle" "double")
set_tests_properties(TestCudaSettleDouble PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;36;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaSortSingle "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaSort" "single")
set_tests_properties(TestCudaSortSingle PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;33;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaSortMixed "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaSort" "mixed")
set_tests_properties(TestCudaSortMixed PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;35;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaSortDouble "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaSort" "double")
set_tests_properties(TestCudaSortDouble PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;36;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaVariableLangevinIntegratorSingle "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaVariableLangevinIntegrator" "single")
set_tests_properties(TestCudaVariableLangevinIntegratorSingle PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;33;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaVariableLangevinIntegratorMixed "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaVariableLangevinIntegrator" "mixed")
set_tests_properties(TestCudaVariableLangevinIntegratorMixed PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;35;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaVariableLangevinIntegratorDouble "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaVariableLangevinIntegrator" "double")
set_tests_properties(TestCudaVariableLangevinIntegratorDouble PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;36;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaVariableVerletIntegratorSingle "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaVariableVerletIntegrator" "single")
set_tests_properties(TestCudaVariableVerletIntegratorSingle PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;33;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaVariableVerletIntegratorMixed "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaVariableVerletIntegrator" "mixed")
set_tests_properties(TestCudaVariableVerletIntegratorMixed PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;35;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaVariableVerletIntegratorDouble "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaVariableVerletIntegrator" "double")
set_tests_properties(TestCudaVariableVerletIntegratorDouble PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;36;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaVerletIntegratorSingle "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaVerletIntegrator" "single")
set_tests_properties(TestCudaVerletIntegratorSingle PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;33;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaVerletIntegratorMixed "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaVerletIntegrator" "mixed")
set_tests_properties(TestCudaVerletIntegratorMixed PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;35;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaVerletIntegratorDouble "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaVerletIntegrator" "double")
set_tests_properties(TestCudaVerletIntegratorDouble PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;36;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaVirtualSitesSingle "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaVirtualSites" "single")
set_tests_properties(TestCudaVirtualSitesSingle PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;33;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaVirtualSitesMixed "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaVirtualSites" "mixed")
set_tests_properties(TestCudaVirtualSitesMixed PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;35;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
add_test(TestCudaVirtualSitesDouble "/home/andy/test_optimization/openmm-8.4.0/build_test/TestCudaVirtualSites" "double")
set_tests_properties(TestCudaVirtualSitesDouble PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;36;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/platforms/cuda/tests/CMakeLists.txt;0;")
