# CMake generated Testfile for 
# Source directory: /home/andy/test_optimization/openmm-8.4.0/serialization/tests
# Build directory: /home/andy/test_optimization/openmm-8.4.0/build_test/serialization/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(TestSerializationNode "/home/andy/test_optimization/openmm-8.4.0/build_test/TestSerializationNode")
set_tests_properties(TestSerializationNode PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/serialization/tests/CMakeLists.txt;19;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/serialization/tests/CMakeLists.txt;0;")
add_test(TestSerializeATMForce "/home/andy/test_optimization/openmm-8.4.0/build_test/TestSerializeATMForce")
set_tests_properties(TestSerializeATMForce PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/serialization/tests/CMakeLists.txt;19;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/serialization/tests/CMakeLists.txt;0;")
add_test(TestSerializeAndersenThermostat "/home/andy/test_optimization/openmm-8.4.0/build_test/TestSerializeAndersenThermostat")
set_tests_properties(TestSerializeAndersenThermostat PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/serialization/tests/CMakeLists.txt;19;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/serialization/tests/CMakeLists.txt;0;")
add_test(TestSerializeCMAPTorsion "/home/andy/test_optimization/openmm-8.4.0/build_test/TestSerializeCMAPTorsion")
set_tests_properties(TestSerializeCMAPTorsion PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/serialization/tests/CMakeLists.txt;19;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/serialization/tests/CMakeLists.txt;0;")
add_test(TestSerializeCMMotionRemover "/home/andy/test_optimization/openmm-8.4.0/build_test/TestSerializeCMMotionRemover")
set_tests_properties(TestSerializeCMMotionRemover PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/serialization/tests/CMakeLists.txt;19;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/serialization/tests/CMakeLists.txt;0;")
add_test(TestSerializeConstantPotentialForce "/home/andy/test_optimization/openmm-8.4.0/build_test/TestSerializeConstantPotentialForce")
set_tests_properties(TestSerializeConstantPotentialForce PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/serialization/tests/CMakeLists.txt;19;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/serialization/tests/CMakeLists.txt;0;")
add_test(TestSerializeCustomAngleForce "/home/andy/test_optimization/openmm-8.4.0/build_test/TestSerializeCustomAngleForce")
set_tests_properties(TestSerializeCustomAngleForce PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/serialization/tests/CMakeLists.txt;19;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/serialization/tests/CMakeLists.txt;0;")
add_test(TestSerializeCustomBondForce "/home/andy/test_optimization/openmm-8.4.0/build_test/TestSerializeCustomBondForce")
set_tests_properties(TestSerializeCustomBondForce PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/serialization/tests/CMakeLists.txt;19;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/serialization/tests/CMakeLists.txt;0;")
add_test(TestSerializeCustomCVForce "/home/andy/test_optimization/openmm-8.4.0/build_test/TestSerializeCustomCVForce")
set_tests_properties(TestSerializeCustomCVForce PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/serialization/tests/CMakeLists.txt;19;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/serialization/tests/CMakeLists.txt;0;")
add_test(TestSerializeCustomCentroidBondForce "/home/andy/test_optimization/openmm-8.4.0/build_test/TestSerializeCustomCentroidBondForce")
set_tests_properties(TestSerializeCustomCentroidBondForce PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/serialization/tests/CMakeLists.txt;19;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/serialization/tests/CMakeLists.txt;0;")
add_test(TestSerializeCustomCompoundBondForce "/home/andy/test_optimization/openmm-8.4.0/build_test/TestSerializeCustomCompoundBondForce")
set_tests_properties(TestSerializeCustomCompoundBondForce PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/serialization/tests/CMakeLists.txt;19;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/serialization/tests/CMakeLists.txt;0;")
add_test(TestSerializeCustomExternalForce "/home/andy/test_optimization/openmm-8.4.0/build_test/TestSerializeCustomExternalForce")
set_tests_properties(TestSerializeCustomExternalForce PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/serialization/tests/CMakeLists.txt;19;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/serialization/tests/CMakeLists.txt;0;")
add_test(TestSerializeCustomGBForce "/home/andy/test_optimization/openmm-8.4.0/build_test/TestSerializeCustomGBForce")
set_tests_properties(TestSerializeCustomGBForce PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/serialization/tests/CMakeLists.txt;19;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/serialization/tests/CMakeLists.txt;0;")
add_test(TestSerializeCustomHbondForce "/home/andy/test_optimization/openmm-8.4.0/build_test/TestSerializeCustomHbondForce")
set_tests_properties(TestSerializeCustomHbondForce PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/serialization/tests/CMakeLists.txt;19;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/serialization/tests/CMakeLists.txt;0;")
add_test(TestSerializeCustomManyParticleForce "/home/andy/test_optimization/openmm-8.4.0/build_test/TestSerializeCustomManyParticleForce")
set_tests_properties(TestSerializeCustomManyParticleForce PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/serialization/tests/CMakeLists.txt;19;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/serialization/tests/CMakeLists.txt;0;")
add_test(TestSerializeCustomNonbondedForce "/home/andy/test_optimization/openmm-8.4.0/build_test/TestSerializeCustomNonbondedForce")
set_tests_properties(TestSerializeCustomNonbondedForce PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/serialization/tests/CMakeLists.txt;19;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/serialization/tests/CMakeLists.txt;0;")
add_test(TestSerializeCustomTorsionForce "/home/andy/test_optimization/openmm-8.4.0/build_test/TestSerializeCustomTorsionForce")
set_tests_properties(TestSerializeCustomTorsionForce PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/serialization/tests/CMakeLists.txt;19;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/serialization/tests/CMakeLists.txt;0;")
add_test(TestSerializeCustomVolumeForce "/home/andy/test_optimization/openmm-8.4.0/build_test/TestSerializeCustomVolumeForce")
set_tests_properties(TestSerializeCustomVolumeForce PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/serialization/tests/CMakeLists.txt;19;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/serialization/tests/CMakeLists.txt;0;")
add_test(TestSerializeDPDIntegrator "/home/andy/test_optimization/openmm-8.4.0/build_test/TestSerializeDPDIntegrator")
set_tests_properties(TestSerializeDPDIntegrator PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/serialization/tests/CMakeLists.txt;19;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/serialization/tests/CMakeLists.txt;0;")
add_test(TestSerializeGBSAOBCForce "/home/andy/test_optimization/openmm-8.4.0/build_test/TestSerializeGBSAOBCForce")
set_tests_properties(TestSerializeGBSAOBCForce PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/serialization/tests/CMakeLists.txt;19;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/serialization/tests/CMakeLists.txt;0;")
add_test(TestSerializeGayBerneForce "/home/andy/test_optimization/openmm-8.4.0/build_test/TestSerializeGayBerneForce")
set_tests_properties(TestSerializeGayBerneForce PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/serialization/tests/CMakeLists.txt;19;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/serialization/tests/CMakeLists.txt;0;")
add_test(TestSerializeHarmonicAngleForce "/home/andy/test_optimization/openmm-8.4.0/build_test/TestSerializeHarmonicAngleForce")
set_tests_properties(TestSerializeHarmonicAngleForce PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/serialization/tests/CMakeLists.txt;19;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/serialization/tests/CMakeLists.txt;0;")
add_test(TestSerializeHarmonicBondForce "/home/andy/test_optimization/openmm-8.4.0/build_test/TestSerializeHarmonicBondForce")
set_tests_properties(TestSerializeHarmonicBondForce PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/serialization/tests/CMakeLists.txt;19;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/serialization/tests/CMakeLists.txt;0;")
add_test(TestSerializeIntegrator "/home/andy/test_optimization/openmm-8.4.0/build_test/TestSerializeIntegrator")
set_tests_properties(TestSerializeIntegrator PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/serialization/tests/CMakeLists.txt;19;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/serialization/tests/CMakeLists.txt;0;")
add_test(TestSerializeMonteCarloAnisotropicBarostat "/home/andy/test_optimization/openmm-8.4.0/build_test/TestSerializeMonteCarloAnisotropicBarostat")
set_tests_properties(TestSerializeMonteCarloAnisotropicBarostat PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/serialization/tests/CMakeLists.txt;19;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/serialization/tests/CMakeLists.txt;0;")
add_test(TestSerializeMonteCarloBarostat "/home/andy/test_optimization/openmm-8.4.0/build_test/TestSerializeMonteCarloBarostat")
set_tests_properties(TestSerializeMonteCarloBarostat PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/serialization/tests/CMakeLists.txt;19;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/serialization/tests/CMakeLists.txt;0;")
add_test(TestSerializeMonteCarloFlexibleBarostat "/home/andy/test_optimization/openmm-8.4.0/build_test/TestSerializeMonteCarloFlexibleBarostat")
set_tests_properties(TestSerializeMonteCarloFlexibleBarostat PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/serialization/tests/CMakeLists.txt;19;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/serialization/tests/CMakeLists.txt;0;")
add_test(TestSerializeMonteCarloMembraneBarostat "/home/andy/test_optimization/openmm-8.4.0/build_test/TestSerializeMonteCarloMembraneBarostat")
set_tests_properties(TestSerializeMonteCarloMembraneBarostat PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/serialization/tests/CMakeLists.txt;19;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/serialization/tests/CMakeLists.txt;0;")
add_test(TestSerializeNonbondedForce "/home/andy/test_optimization/openmm-8.4.0/build_test/TestSerializeNonbondedForce")
set_tests_properties(TestSerializeNonbondedForce PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/serialization/tests/CMakeLists.txt;19;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/serialization/tests/CMakeLists.txt;0;")
add_test(TestSerializeNoseHooverIntegrator "/home/andy/test_optimization/openmm-8.4.0/build_test/TestSerializeNoseHooverIntegrator")
set_tests_properties(TestSerializeNoseHooverIntegrator PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/serialization/tests/CMakeLists.txt;19;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/serialization/tests/CMakeLists.txt;0;")
add_test(TestSerializeOrientationRestraintForce "/home/andy/test_optimization/openmm-8.4.0/build_test/TestSerializeOrientationRestraintForce")
set_tests_properties(TestSerializeOrientationRestraintForce PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/serialization/tests/CMakeLists.txt;19;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/serialization/tests/CMakeLists.txt;0;")
add_test(TestSerializePeriodicTorsionForce "/home/andy/test_optimization/openmm-8.4.0/build_test/TestSerializePeriodicTorsionForce")
set_tests_properties(TestSerializePeriodicTorsionForce PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/serialization/tests/CMakeLists.txt;19;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/serialization/tests/CMakeLists.txt;0;")
add_test(TestSerializeQTBIntegrator "/home/andy/test_optimization/openmm-8.4.0/build_test/TestSerializeQTBIntegrator")
set_tests_properties(TestSerializeQTBIntegrator PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/serialization/tests/CMakeLists.txt;19;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/serialization/tests/CMakeLists.txt;0;")
add_test(TestSerializeRBTorsionForce "/home/andy/test_optimization/openmm-8.4.0/build_test/TestSerializeRBTorsionForce")
set_tests_properties(TestSerializeRBTorsionForce PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/serialization/tests/CMakeLists.txt;19;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/serialization/tests/CMakeLists.txt;0;")
add_test(TestSerializeRGForce "/home/andy/test_optimization/openmm-8.4.0/build_test/TestSerializeRGForce")
set_tests_properties(TestSerializeRGForce PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/serialization/tests/CMakeLists.txt;19;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/serialization/tests/CMakeLists.txt;0;")
add_test(TestSerializeRMSDForce "/home/andy/test_optimization/openmm-8.4.0/build_test/TestSerializeRMSDForce")
set_tests_properties(TestSerializeRMSDForce PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/serialization/tests/CMakeLists.txt;19;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/serialization/tests/CMakeLists.txt;0;")
add_test(TestSerializeState "/home/andy/test_optimization/openmm-8.4.0/build_test/TestSerializeState")
set_tests_properties(TestSerializeState PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/serialization/tests/CMakeLists.txt;19;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/serialization/tests/CMakeLists.txt;0;")
add_test(TestSerializeSystem "/home/andy/test_optimization/openmm-8.4.0/build_test/TestSerializeSystem")
set_tests_properties(TestSerializeSystem PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/serialization/tests/CMakeLists.txt;19;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/serialization/tests/CMakeLists.txt;0;")
add_test(TestSerializeTabulatedFunctions "/home/andy/test_optimization/openmm-8.4.0/build_test/TestSerializeTabulatedFunctions")
set_tests_properties(TestSerializeTabulatedFunctions PROPERTIES  _BACKTRACE_TRIPLES "/home/andy/test_optimization/openmm-8.4.0/serialization/tests/CMakeLists.txt;19;ADD_TEST;/home/andy/test_optimization/openmm-8.4.0/serialization/tests/CMakeLists.txt;0;")
